### ISSUE TITLE
Profiles, e.g. behave differently according to power source

### ISSUE THREAD

**Issue by wizonesolutions** [deanoemcke/thegreatsuspender#103]
When I am on the move, it's nice to extend battery life a bit by suspending/closing unneeded processes. Does the Chrome API tell you if the user is on battery power or not? If so, it'd be cool if I could tell TGS not to suspend anything when I'm plugged in, or maybe to only suspend certain things I care less about. Whereas when on battery I want to suspend all heavy JS web apps (Gmail, JIRA, IRCCloud, whatever) pretty quickly after leaving them as long as there are no dirty forms (which has its own setting anyway).

**Comment by wizonesolutions** [comment]
@deanoemcke Now that the beta (new version?) is further along, do you have any thoughts on this? Often I use the extension most when I am out and about in order to save power-hungry Chrome tabs from being quite so power-hungry. At such times, I want the extension to be somewhat aggressive. But when I am plugged in, I'd probably like the time-to-suspension to be higher, and often I feel like I'd even like a separate (narrower) whitelist. e.g. if plugged in, I don't suspend GitHub or JIRA but if I'm on battery I do. Something like that.

**Comment by deanoemcke** [comment]
I've done a bit of research and there doesn't appear to be any way for a chrome extension to detect a change in the power source. 
Perhaps a solution could be to be able to switch 'profiles' in the extension, so when you're on battery power you can change your profile to be more aggressive.
Alternatively (and possibly easier to implement) could be a button that simply pauses suspension on all tabs so that when you're plugged in to power, the extension will not attempt to suspend any new tabs.

I'll leave this issue open, but will not implement anything like this just yet. Right now my focus is fixing bugs, improving stability, and getting the extension updated on the webstore.

**Comment by deanoemcke** [comment]
This has now been implemented in the latest gitHub version.
Chrome webstore release following shortly.
