### ISSUE TITLE
Feature request: only suspend on low ram

### ISSUE THREAD

**Issue by thegoodhen** [deanoemcke/thegreatsuspender#170]
Hello, I haven't looked into chrome extension development deep enough, so I am not sure if it's possible; However, if it is, it'd be greatly appreciated if the extension could keep track of the total memory used by the system and only start suspending the tabs once the system is running low on memory. Chrome would use up as much memory as it'd like to, but once other apps would need some too, it'd move out of the way...

**Comment by aug-riedinger** [comment]
:+1:

**Comment by aug-riedinger** [comment]
Now that I think again about it, I am (unfortunately) almost sure this is not possible. 

But instead of looking at system's memory (which may not be accessible), I'd look at tabs' memory leaks, which can pretty often be a big issue.

Eg. 
Using a tab that uses 140mo RAM, and going away.
After 30 minutes, the app is in the background, but now uses 200mo RAM. ==> Suspend it.

What do you think?

**Comment by deanoemcke** [comment]
I have great plans for this extension in the realm of analysing memory statistics. However, chrome does not currently have any APIs that allow me to access this data. Or to be more accurate, there ARE apis (specifically the chrome.processes API), but they are only available on the development channel which excludes the majority of users. Once these APIs make it into stable, I'll look at implementing some smarter memory management processes. To be honest, when these new APIs come out, the whole way this extension works will be able to change dramatically.
