### ISSUE TITLE
new incognito session makes welcome tab appears

### ISSUE THREAD

**Issue by jvbridge** [deanoemcke/thegreatsuspender#182]
When starting a new incognito session (opening a new incognito tab when none are currently open) the welcome tab appears for The Great Suspender. 
![screen shot 2015-04-21 at 8 02 54 pm](https://cloud.githubusercontent.com/assets/6423593/7266628/6ec24ee6-e861-11e4-8d7f-ea283b386c8d.png)

**Comment by thisisjeron** [comment]
Found this issue after recently installing The Great Suspender. Hope deanoemcke sees this.

**Comment by deanoemcke** [comment]
Thanks for the fix @matheod 
Been meaning to address this for a while :)

**Comment by bulutcy** [comment]
Hi, 
Is this fix released on Chrome Web Store? I'm still getting Welcome page in incognito window.
Thanks.

**Comment by bassmadrigal** [comment]
@bulutcy, I know I'm late to this, but hopefully this will help you or any others coming across this bug. I was still running into this issue, which led me to look to see if it'd been reported. After seeing that a fix was released, I started digging more. Turns out the updated extension never got pushed to my browser. I was still running 6.14. I just uninstalled the extension and then reinstalled it, and now I have 6.21 (which does contain the fix).
