### ISSUE TITLE
Feature request: Have suspended tab title displayed across synced devices. 

### ISSUE THREAD

**Issue by rattasak** [deanoemcke/thegreatsuspender#184]
It would be nice to have the original tab titles displayed when viewing tabs across synced devices. Right now, when viewing suspended tabs on computer A from computer B using Chrome's syncing feature, the titles for all suspended tabs are displayed as "Suspended Tab". 

I'm not sure how difficult this would be to add, but I think it would be a really helpful feature since people that use this extension probably have a habit of having a lot of tabs open in general. 

Thanks.

**Comment by deanoemcke** [comment]
@rattasak This has been requested before in #164. As mentioned there, this has been fixed in the development version of the extension. It will be released to the chrome webstore shortly - however, it will not be rolled out automatically. You will need to do an uninstall/reinstall to upgrade. NOTE: be sure to unsuspend all your tabs before you attempt this!

**Comment by rattasak** [comment]
Ah great to know. Sorry about the duplicate feature request.

**Comment by deanoemcke** [comment]
It turns out this does not work as intended. I'm re-opening the original issue to reflect this.
