### ISSUE TITLE
Disable/Uninstalling destroys open suspended tabs

### ISSUE THREAD

**Issue by terado** [deanoemcke/thegreatsuspender#216]
When uninstalling extension the open tabs that have been suspended are then destroyed. When disabling extension they are closed until re-enabling.

Ideally one would expect the open tabs to be restored as open and un-suspended.

Suggestions
If no hook is accessible during disable/uninstall perhaps these suggestions are available:
- At install time (introduction) and in the options tab it could make very clear that disabling or uninstalling will remove the tabs and perhaps provide a button to unsuspend all tabs before doing this.
- Currently the suspended tabs are tied into the extension Chrome URL - perhaps instead a local file or local micro webserver could exist to serve the interstitial page, yet would not vanish.

**Comment by deanoemcke** [comment]
@terado I completely agree with your desired / expected behaviour. And you are correct that there is no disable / uninstall hook available.

I have thought about including a warning message on extension install and may still do this. But I feel that the chances of this information being properly digested and actually remembered / acted upon when the user goes to uninstall is slim. There is already a button to unsuspend all tabs, but once again, there is no way to direct the user to this button at the relevant time (when they go to uninstall).

The fact that the suspended pages are tied to the extension process is unavoidable for now. There ARE local files that get served, but the still belong to the extension process - there is no getting around this. The extension runs in a sandbox, and any functionality it provides is revoked when the extension is uninstalled.

**Comment by joeytwiddle** [comment]
If you are suffering from this, this little bookmarklet may help...

1. Hit Ctrl-Shift-B to show your Bookmarks Toolbar.

2. Create a new "page" there, call it `Unsuspend` and give it the following URL:

        javascript:document.location=decodeURIComponent(document.location.hash.replace(/.*url=([^&]*).*/,'$1'));(void 0);

3. The next time you are on a suspended page, tap that bookmarklet and it will unsuspend.  :)

**Comment by deanoemcke** [comment]
@joeytwiddle perhaps you would like to share your bookmarklet on the issue below? I suspect it will need a little tweaking. As it uses uri now instead of url..

Please refer to this guide on why this happens and how to recover lost tabs: #526
