### ISSUE TITLE
Tab Flashing

### ISSUE THREAD

**Issue by entozoon** [deanoemcke/thegreatsuspender#218]
![image](https://cloud.githubusercontent.com/assets/5763772/7880150/e267bb74-05ee-11e5-87c9-b07d0f34f849.png)

When a tab is suspended (as you can see here with some pinned tabs), they start flashing.
Can there please be an option to turn that off as.. it's really annoying to look at.

I know that it's usually caused by javascript modifying the site's title, although they seem to remain the same after suspension so I wonder why it's caused.

**Comment by deanoemcke** [comment]
@entozoon Unfortunately I think this is unavoidable. You are correct that it's due to the tab's title and favicon being updated. When a tab is suspended, what actually happens is it navigates the tab to a new url. That url initially has a default favicon (as shown in your screenshot). Once the new page loads, it uses js to update the title and favicon to match that of the page that was suspended.

the only thing i could do to improve this is to change the default favicon, but it would not fix the 'flashing' issue unfortunately.
