### ISSUE TITLE
Suspend pages opened in new tabs

### ISSUE THREAD

**Issue by tkapler** [deanoemcke/thegreatsuspender#228]
I wonder if it would be possible to automatically suspend all tabs opened in a new tab (so In background), so that they would be not loaded at all until the tab get focus

**Comment by deanoemcke** [comment]
It would be a great feature, however it may be tricky to implement in practice.
In order to find out the page favicon and title, I would first need to load the page and then suspend it (somewhat defeating the purpose of this feature).
Interested to hear workarounds for this, but for now I'll leave this.

**Comment by deanoemcke** [comment]
I have implemented this in the latest version (not on the webstore yet). The extension now has a new right-click option to 'open in new suspended tab'
To get around the issues mentioned above, the newly suspended tab will use the title and favicon from the original tab (the one containing the link).

**Comment by deanoemcke** [comment]
This feature is now available in the chrome webstore on v6.30.

**Comment by deanoemcke** [comment]
Just an update on this issue. The current functionality of 'open link in new suspended tab' will now actually wait until the tab has fully loaded in the background and THEN suspend it. 
This is so that i can capture the favicon, page title, and optionally take a screencapture, before suspending the tab.
More info of this can be found here: https://github.com/deanoemcke/thegreatsuspender/issues/572
