### ISSUE TITLE
Keep scroll location

### ISSUE THREAD

**Issue by jamesonquinn** [deanoemcke/thegreatsuspender#229]
It would be nice if suspended screenshots could keep the same scroll position as the tab was in. Sometimes, I’m keeping a tab open as a reference — for instance, I’m looking back and forth between a document I’m creating and a graph, table, or image that has information I’m using. In that case, having the page “reset” to the top of the page means I have to re-awaken it, while if it stayed in the same position I could leave it suspended.

This is related to issue #217, but it's not quite the same thing.

**Comment by Diablo-D3** [comment]
This is a major issue that I also wish would get resolved.

I use auto-unsuspend with screen capturing, being able to stay at the same scroll location while suspending and unsuspending would be very useful.

**Comment by joshtronic** [comment]
:+1:

**Comment by DanAtkinson** [comment]
:+1: This really gets annoying for me. Shouldn't be too hard to keep track of current scroll location when the page is suspended and then reloaded. Once it has reloaded, I'd expect a wait period of, say a few seconds before the scroll position is re-applied (to ensure that any resources such as AJAX content/images have chance to reload.

**Comment by Diablo-D3** [comment]
Yeah' something like doing this in a window.onload and waiting 2 seconds
would work for most people.

**Comment by deanoemcke** [comment]
This issue is for remembering the scroll position in the *screen capture* (ie. the captured screen can be from part way down the page). However it seems a few people are confusing this with the request to remember scroll position on reload. 
The latter functionality was initially completed in #43 and should work as expected in the latest version (v6.19). If you are finding that it does not remember scroll position on page reload, then can you please raise a separate bug for this.

**Comment by Diablo-D3** [comment]
Yes, it now restores the original position. It is just now confusing because it doesn't also scroll the screen shot.

**Comment by quaertym** [comment]
:+1:
