### ISSUE TITLE
Ability to import a session

### ISSUE THREAD

**Issue by snekse** [deanoemcke/thegreatsuspender#247]
The Session Management tools let you save or export a session.  You can reload a saved session, but not one that has been exported.

I'd like the ability to import an external session as a Saved Session.  From there, you can reload it like any other session.

**Comment by jpagarcia** [comment]
Agree

**Comment by zattack96** [comment]
+1

**Comment by deanoemcke** [comment]
As mentioned in https://github.com/deanoemcke/thegreatsuspender/issues/481 improvements to the session management feature are not a priority. 

As a workaround for now, Session Buddy is a great session management tool and is a better alternative than relying on The Great Suspender. Session Buddy can also import sessions exported with The Great Suspender.

**Comment by deanoemcke** [comment]
So much for that. Session importing has now been implemented: https://github.com/deanoemcke/thegreatsuspender/commit/d0f0df97bcfcc6567c2f014f5fea1b799d93ab2a

**Comment by oshipper** [comment]
Can we turn off the session management features? It has been causing massive performance issues and battery drain since introduction.

Why can't we turn it off? Can you please add a toggle switch?

Since this feature was added my Chrome maxes out a CPU core and slows to a crawl. 32gb ram 8850h 2tb nvme drive; I should not have any issues.

Maybe I'm a special case. I keep ~1600 tabs open. Previous version had no problems with 2000+ tabs though.

I have another extension for managing sessions (FreshStart). It does fine.

**Comment by deanoemcke** [comment]
@oshipper What version of the extension are you using? There are a few performance issues in the most recent webstore version (v7.0.109) which I have been ironing out.
The latest development build is MUCH more performant.

Here is the relevant issue for addressing ongoing performance issues: #793 

As for toggling off session management features. Unfortunately that is not an option. This has been requested before near the end of this thread: #781 
Reproduced here for convenience:

> ...wouldn't it be easier for YOU to add a simple enable/disable killswitch (checkbox) at the top of the session management page so those like me that don't even use TGS session management can disable it? Then if we need to report an issue to you, our report automatically eliminates half the code-base dealing with sessions not to mention all that code overhead that never would need to execute.

I understand your frustration here. But if there's a bug, I'd rather identify it and fix it, rather than provide an option to turn off some valuable functionality. If said functionality was turned off manually by a user, then when the extension updates all of their suspended tabs would disappear and WOULD NOT come back. This is not really an option.

Let me know if you need any clarification on this.

**Comment by oshipper** [comment]
I was using the latest chrome store one. 

Went thru hell of un suspending 1700 tabs and then changing over to the development build and resuspending. So far performance is much better.

One question though, once an update(s) is available (beta or stable) will I have to lose all suspended tabs again in order to update?
