### ISSUE TITLE
Change position multiple tabs in multiple Windows

### ISSUE THREAD

**Issue by rogama** [deanoemcke/thegreatsuspender#297]
I found a issue
I have configured the extension for 10 minutes to suspend the windows open, I usually work with multiple windows and these at the same time with multiple tabs.

When suspends the tabs window changes, that is, if I have:
Window 1:
-> Tab 1
-> Tab 2
-> Tab 3

Window 2:
-> Tab 4
-> Tab 5
-> Tab 6

I changed it to something like this:
window 1
-> Tab 1
-> Tab 6
-> Tab 4

Window 2:
-> Tab 2
-> Tab 3
-> Tab 5

**Comment by max-webster** [comment]
I experienced this same issue. It was quite obvious because I typically have one OS X 'space' with personal browser windows and another with work-related ones, and I would find tabs with news articles or Amazon orders in the middle of windows containing a dozen tabs for JIRA issues. Also, I found that I had at least 2 of each open tab, again scattered between various windows. I only installed Great Suspender yesterday - this behavior occurred on my desktop but not my laptop. I'll keep an eye out for other symptoms and reproducibility. I have blocked the Google software updater on some computers so I think the level of Chrome and Great Suspender is higher on the machine where the problem occurs than the one where it doesn't. I'm seeing the problem on Chrome 45.0.2454.85 + Great Suspender 6.13.

**Comment by max-webster** [comment]
I had to shut off the extension because after a day of leaving the browser running, I had about 15 copies of each tab (all suspended, scattered among random windows). I restarted Chrome but the duplication kept happening.

**Comment by deanoemcke** [comment]
@max-webster can you try uninstalling your current version and reinstalling the latest one from the webstore (v6.21)? there have been some issues with older versions of the extension with chrome v45 which have now been fixed. 

IMPORTANT: Before uninstalling, make sure you unsuspend all currently suspended tabs. Also, this will delete your whitelist and any saved sessions you have created, so you will need to export these before you update.

Please let me know if this resolves your issue.

**Comment by max-webster** [comment]
Yes, reinstalling with 6.21 fixed, thanks.
