### ISSUE TITLE
Chrome crashing 3+ times a day

### ISSUE THREAD

**Issue by guillermovs** [deanoemcke/thegreatsuspender#30]
I really like your extension, but ever since I installed it Chrome (25.0.1364.152) is crashing at least 3 times a day. Do you know what could be causing this?

Thanks!

**Comment by KoltonG** [comment]
+1 For Crashing

**Comment by deanoemcke** [comment]
@KoltonG could you let me know your chrome version, extension version, and also operating system? And also, do you have screen capturing turned on?
How often is it crashing? And is it while you are doing something in particular?

**Comment by KoltonG** [comment]
Chrome Version: 42.0.2311.152 (64-bit)
Extension Version: 4.74
Operating System: OSX 10.9.5 (Build 13F34) Mavericks

No Screen Capture

It crashed pretty often, I would reload the extension and within 10-20 mins it would say that it has crashed and it says in the popup to click to reload, but then it just crashes again at the same interval.

I usually have 30 + tabs, and just random I guess

**Comment by deanoemcke** [comment]
@KoltonG ok. first thing to do is upgrade to latest version v6.16. i'm faily confident this will resolve your issue. due to the nature of the extension, if i force an update out, it can cause users to lose their suspended tabs for ever. because of this, i have disabled automatic updating. you should be able to manually update, or uninstall and reinstall from the webstore. IMPORTANT: make sure you unsuspend all tabs before doing this to prevent them from being lost.
Let me know if the newer version seems more stable.

**Comment by jonathancast** [comment]
The extension is crashing for me on Chrome start-up, and crashes again every time I reload it.  It takes about 2 seconds to crash if I reload it.

Chrome version:  Version 53.0.2785.143 Built on Ubuntu , running on Ubuntu 16.04 (64-bit)
Extension version: 6.21
Operating system: Linux 4.4.0-43-generic #63-Ubuntu SMP
Running KDE Plasma 5.5.5
