### ISSUE TITLE
show URL on the tab suspended page

### ISSUE THREAD

**Issue by xurei** [deanoemcke/thegreatsuspender#309]
Since the title is not always very self-explanatory on some pages, showing the URL would be great to know the page we are looking at is the one we are looking for.

**Comment by deanoemcke** [comment]
@xurei as a work around for this, you can hover over the page title (it's a hyperlink) and see the actual page url in the status bar at the bottom.

**Comment by aziraphale** [comment]
Related to this, if you use Chrome on Android, with tabs synced between your PC and your phone, going into Android-Chrome's list of tabs open on your PC (i.e. Menu -> Recent Tabs) just shows a huge list of "Suspended Tab" entries instead of any kind of indication of what page was suspended for each of those tabs. If the URL/title was displayed, I could at least open a suspended tab on my phone and manually remove the "chrome-extension://......" part of the URL to get back to the live page, but that's impractical when all I see is dozens upon dozens of identically-named tabs...

**Comment by deanoemcke** [comment]
I've also now added a tooltip when hovering on the title in the suspended tab. Still not sure if I want the url to display permanently here..

**Comment by PureLines** [comment]
Please, add an option to show full URL below the page title in the suspended tab.

**Comment by xurei** [comment]
+1. When you have a lot of opened tabs, it's really helpful. A tooltip is nice but still takes too long with multiple tabs.

**Comment by deanoemcke** [comment]
implemented in: https://github.com/deanoemcke/thegreatsuspender/pull/649
