### ISSUE TITLE
Active tabs convert to suspending tab *PLZ FIX IT*

### ISSUE THREAD

**Issue by qu1cksilver** [deanoemcke/thegreatsuspender#311]
**[same problem]**

Like a few others here I am experiencing a problem, when a tab pauses, the other active tabs all automatically pause and their url changes to that of the paused tab. I have to then search my history for what I was looking at, very frustrating.

**[THE BUG CONTINUES]**

Great extension. But I regret to inform you this bug is still occurring and are pulling my hair because there's no way to know which page was previously.

**[if the case is useful]**

I was observing the task manager of Chrome and I noticed that your Extension is suspending other guides also because it suspends by the process id and the Chrome do not know why, it cluster some tabs in the same process id, so when your Extension suspends some correct tab, unintentionally, other guides that are in the same process id, improperly end up being suspended as well.

I do not know whether is possible, but you should also save a string with the title of the tab beyond her process id, with an If you solve this problem and would not have undue guides being suspended and overlapping

I'm sorry for my bad English

I use Chrome v. 47.0.2526.8 dev-m

**Comment by dt-rush** [comment]
This should be fixed if you upgrade to [chrome 46](https://code.google.com/p/chromium/issues/detail?id=529059#makechanges)

**Comment by bro3234** [comment]
I'm experiencing this same bug on Chrome Version 47.0.2526.27 beta (64-bit).

**Comment by deanoemcke** [comment]
@qu1cksilver @bro3234 
This bug was fixed in version 6.21 of the chrome extension. However, automatic updating for this extension has been disabled so you will need to upgrade manually by uninstalling and reinstalling the extension.
IMPORTANT: Make sure you unsuspend all tabs before doing this! Also, you will lose your whitelist and any saved sessions you have created so you might want to back them up first.

Please let me know if upgrading does not fix your issue.

**Comment by bro3234** [comment]
I haven't been experiencing this bug lately.  Didn't have to uninstall and reinstall either.
