### ISSUE TITLE
Extension does not automatically update

### ISSUE THREAD

**Issue by alidan** [deanoemcke/thegreatsuspender#322]
chrome store says its on version   6.21
the version it says is installed in chrome is 4.74

the reason this was brought to my attention was some tabs refuse to suspend now... seeing that its likely not an issue with tgs being old and likely a change in chrome, i dont think i need to have it updated immediately, but a way to solve this issue would be nice.

**Comment by dungsaga** [comment]
in #312, the author said that:
> A long time ago I decided that automatically updating the extension was too risky as it removes all suspended tabs from the users browser. Hence, the extension does not automatically update.

I wonder if he has plan to enable auto-update again.

**Comment by ptnik** [comment]
At least a warning message stating there was a new version available (and that you should unsuspend all tabs before updating) would be nice.

**Comment by alidan** [comment]
ok, makes sense.

**Comment by deanoemcke** [comment]
@dungsaga I do actually have a plan to reenable automatic updates. there is actually some pretty solid tab recovery functionality which i'm fairly confident in. but it only works for people coming from a version of the extension where this has actually been implemented :) 
however, it looks like there are very few people on the old 4.x versions now which opens this up as a possibility.

If you want to give it a test, try going to the extension management page and disable then re-enable the extension. You should get to a recovery screen which will reload all your suspended tabs.

I am considering turning on automatic updates very soon.

**Comment by alidan** [comment]
just for anyone who keep an absolute shit ton of tabs open and is on an older version of the extension, session buddy lets you save the entirety of what you have open, and should be recoverable if you quit the extension to update. i dont get to shut chrome down much as re opening 400~ tabs kind of takes a long, long time to do.

**Comment by dungsaga** [comment]
@deanoemcke what is the earliest version where you implemented it?

**Comment by yrro** [comment]
Having just logged on to a computer that I haven't used for a couple of years, and found an older version of the extension running... what _is_ the process for updating from an older version of the extension--remove from Chrome & add again?

**Comment by alidan** [comment]
Ok, just upgraded from version 4.74 to newest on the google store... 
all i can say is holy shit. 
this extension got really good, and i'm sad i didn't update sooner. 

now, to tell you how i updated

closed chrome, but saved session in session buddy, prepared to all links i had open (152) and rest computer, restarted, and chrome crashed so restarted it again and it didnt try to open all the tabs this time, backed up version 4.74 and removed it, got newest, and every link worked, nothing lost. 

to the person making this extension, you should shill out session buddy too, its a fantastic companion extension for this.

**Comment by deanoemcke** [comment]
Just an update on my thoughts regarding keeping the extension up to date in the chrome webstore. 

Until further notice I will NOT be enabling automatic updates on the chrome webstore version of the extension. This is due to the aforementioned issue whereby users lose all their suspended tabs when the extension attempts to update. My reasoning is that the benefits from the newer features and bugfixes do not outweigh the negative experience of having all your tabs disappear and potentially not being able to recover them.

My stance on this may change if a newer version of chrome is released that causes the extension to horribly break.

However, I WILL endeavour to keep the chrome webstore version up to date with gitHub. But the newer version will only be available to new users, or users that uninstall the extension and reinstall it. ie. no automatic updates. If you want the latest version you will need to update manually. Hopefully this will help you manage the upgrade and ensure you don't lose any tabs in the process.

For those wanting to update (the current webstore version is v6.21 but will soon be replaced with v6.30), here is my suggested upgrade process:

1. Install the session buddy extension (https://chrome.google.com/webstore/detail/session-buddy/edacconmaakjimmfgnblocblbcdcpbko?hl=en).
2. Save your current session in session buddy, and then (just to be safe) UNSUSPEND all tabs and then do another session buddy save. The reason for this is that the urls of suspended tabs are linked to the extension id, and if this changes for any reason after reinstalling the extension, none of your suspended tabs (from the first session save) will restore properly.
3. Copy and paste you whitelist contents into a text editor as a backup.
4. Now uninstall and reinstall the extension. This should put you on the latest version.

**Comment by ShalokShalom** [comment]
Maybe simply notify, when a new version comes up and signal the issue?
Or create a specific place, where the tabs get stored and restore them, once the upgrade is done?

**Comment by decadent** [comment]
> But the newer version will only be available to new users, or users that uninstall the extension and reinstall it.

Just in case this doesn't work (I didn't even know it's an option): wouldn't it be possible to release the new version as a different extension, something like "The Great Suspender Updated"? So that only people prepared to lose the tabs uninstall the current extension and get the new one, just like with the proposed approach.

**Comment by ShalokShalom** [comment]
I think this can also be "The Great Suspender BETA"

Humans, which are brave enough to let their tabs go, are also brave enough to test, yes? ;)

"Updated" suggests, that the other version is outdated, which is quite unpopular among the users, so a lot of the new users install the updated version then. Same with something like "Auto-update"

Users mostly dont know, what they want ;)

**Comment by deanoemcke** [comment]
I have found a way to make the extension update process manageable and will be changing my policy on 'no updates'. See the relevant feature issue here: https://github.com/deanoemcke/thegreatsuspender/issues/609

I will still endeavour to keep updates to a minimum however, as the process will still be a little disruptive.
