### ISSUE TITLE
Tracking through Doublick.net and Google Analytics

### ISSUE THREAD

**Issue by shaneonabike** [deanoemcke/thegreatsuspender#333]
Thanks for a great module!

I was wondering why your module is sending my data to Google analytics and Doubleclick.net? Doesn't that mean that you are essentially tracking whatever page that I am currently using? I really like this module extension but I didnt see in your agreement that you request to send my personal data around :-1:

**Comment by deanoemcke** [comment]
I do send some data to google analytics. But it is only data to do with the extension page views, nothing to do with the webpages you are actually viewing. I DO NOT TRACK your browser history in any way.
The google analytics data is just to give me an idea of what features people are using to help me improve the extension in future.
I also have nothing to do with doubleclick.net. This is most likely being caused by some other extension.
Feel free to check out the source code here in the project. You will see there is no malicious tracking going on and also no references to doubleclick.net.

**Comment by shaneonabike** [comment]
Hmmm I don't really have any other plugins besides ones that block sites
and third-party cookies.

I'll have a look at your code for sure. Would it be possible that you
included hte option to turn off Google Analytics in the settings?

Cheers

On 2015-12-18 12:04 AM, Dean Oemcke wrote:
>
> I do send some data to google analytics. But it is only data to do
> with the extension page views, nothing to do with the webpages you are
> actually viewing. I DO NOT TRACK your browser history in any way.
> The google analytics data is just to give me an idea of what features
> people are using to help me improve the extension in future.
> I also have nothing to do with doubleclick.net. This is most likely
> being caused by some other extension.
> Feel free to check out the source code here in the project. You will
> see there is no malicious tracking going on and also no references to
> doubleclick.net.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/deanoemcke/thegreatsuspender/issues/333#issuecomment-165665640>.
>

-- 

Shane Bill

Web Developer & Consultant

E-mail 	shane@beesonabike.com <mailto:shane@beesonabike.com>
Mobile 	(514) 608-8068
Phone 	(418) 969-2334
More information 	https://develop.beesonabike.com

**Comment by deanoemcke** [comment]
See here for feature request to allow disabling of google analytics: #202
