### ISSUE TITLE
Unsuspend All Tabs does not work

### ISSUE THREAD

**Issue by redolent** [deanoemcke/thegreatsuspender#352]
Here's what I did to produce the error:
1. Had my time set on 1 hour
2. Went to lunch
3. Unsuspended tabs via the menu – all the tabs in just the window were restored
4. Went to the other window, clicked unsuspend
5. Tabs were not restored

Thank you!

**Comment by altern8tif** [comment]
Possibly related issue: "Unsuspend All Tabs" option does not unsuspend all the tabs in a window (only the currently active tab).  I suspect the new Chrome release could have broken the function somewhere since this issue only surfaced in recent weeks.

I am currently running v6.21 on Chrome 47.0.2526.111 on Mac OSX El Capitan.
