### ISSUE TITLE
Access page using URL if ID not in db anymore

### ISSUE THREAD

**Issue by lrq3000** [deanoemcke/thegreatsuspender#365]
Let's say you bookmark a tab that was suspended by TGS. If later TGS crashes and somehow the db gets lost, then opening the bookmark (or history or just URL generated by TGS) will result in TGS redirecting to a blank page instead of the correct webpage.

I think this happens because the ID generated by TGS isn't in its database anymore. But **the original URL is still in the TGS generated URL**, so I think **TGS should failback to extract and open the original URL** in case the ID isn't in db anymore.

This way, even if some info is lost, the webpage will always be accessible via TGS using this simple trick, even if the db crashes.

**Comment by lrq3000** [comment]
An example of what I mean: the following link should work on any browser having TGS installed, but it doesn't:

[chrome-extension://klbibkeccnjlkjkiokjodocebajanakg/suspended.html#url=http%3A%2F%2Fwww.ncbi.nlm.nih.gov%2Fpmc%2Farticles%2FPMC4147439%2F](chrome-extension://klbibkeccnjlkjkiokjodocebajanakg/suspended.html#url=http%3A%2F%2Fwww.ncbi.nlm.nih.gov%2Fpmc%2Farticles%2FPMC4147439%2F)

**Comment by zldrq** [comment]
yeah, that one is needed!
also would be great to save and load TGS db on demand (and auto-backup once a day on the drive or to dropbox/gdrive)
on rare occasions TGS crashes and everything is lost, which is a big deal for me (that was happening on updates also)

but, actually, since i have Session Buddy now, just having a feature, suggested by topicstarter will be sufficient.
i'll try to implement it in my spare time and do a pull request. i never learned javascript know javascript, but i think that task will be feasible for me

**Comment by lrq3000** [comment]
That would be great Zldrq! I know a bit of javascript but I don't know how
to develop extensions so I cannot really do such a change on my own :(

2016-02-21 6:49 GMT+01:00 zldrq <notifications@github.com>:

**Comment by lrq3000** [comment]
@zldrq I implemented the feature myself, you can try the PR, from my own tests it works great :)

**Comment by lrq3000** [comment]
Also, TGS seems to work great with Tabs Outliner, and you can export all your tabs (so it's somewhat a database export) by using [TabAttack](https://github.com/JannesMeyer/TabAttack) or [Copy as Markdown](https://github.com/chitsaou/copy-as-markdown) (both are opensource).

**Comment by deanoemcke** [comment]
I have added support for the older style url= suspended tabs as a fallback. I doubt there's really any out there anymore however.
