### ISSUE TITLE
I love this addon. I need for opera and firefox.

### ISSUE THREAD

**Issue by criminal1** [deanoemcke/thegreatsuspender#373]
I love this addon. I need for opera and firefox. Thanks.

**Comment by criminal1** [comment]
Where are you devs? :)

**Comment by joeytwiddle** [comment]
I don't know of any way to force Firefox to suspend tabs, but if you have Firefox configured to bring back your tabs, you could try restarting it.

When you start Firefox with lots of tabs in the session, it only actually loads the current focused tab. The others don't load until you switch to them, much like TGS's behaviour.

**Comment by joeytwiddle** [comment]
If you are happy to run userscripts, you can try my old [Hibernate Idle Tabs](https://openuserjs.org/scripts/joeytwiddle/Hibernate_Idle_Tabs) scripts. It's a poor man's TGS, but it might be better than nothing while you are waiting. ;)

**Comment by andreicristianpetcu** [comment]
I made an unofficial WebExtension [build for Firefox](https://andreicristianpetcu.github.io/chrome2firefox/addons/unofficial_the_great_suspender-6.21-an+fx.xpi). It does not work exactly as in Chrome but it should be decent. I made no change to the extension from Chrome Web Store. I just renamed it and signed it. It basically "Just works". Please try it in [Firefox Nightly](https://www.mozilla.org/en-US/firefox/nightly/all/) or [DevEdition](https://www.mozilla.org/en-US/firefox/developer/) since Firefox stable might have some missing APIs. Enjoy!

**Comment by deanoemcke** [comment]
For potential firefox port, please refer to this issue: https://github.com/deanoemcke/thegreatsuspender/issues/409
For opera port, refer to this issue: https://github.com/deanoemcke/thegreatsuspender/issues/124
