### ISSUE TITLE
Chrome 50 silently unloads tabs even if whitelisted

### ISSUE THREAD

**Issue by maxxyme** [deanoemcke/thegreatsuspender#398]
Hi,

I recently updated my browser to Chrome 50.
And soon I noticed that numerous tabs which I whitelisted in The Great Suspender, are still being unloaded (after some period of time, don't know how much).
That is really annoying, esp. if I chose "Don't suspend for now" because I was reading something on the page, and now when reloaded, the page is scrolled at the top.

Seems like this isn't a really recent feature, see: https://developers.google.com/web/updates/2015/09/tab-discarding?hl=en

**Comment by Diablo-D3** [comment]
As far as I know, Chrome still has not enabled tab discarding by default.

Also, thegreatsuspender does not use Chrome's discarding logic (although it would be neat if it could).

**Comment by deanoemcke** [comment]
I believe that tab discarding IS enabled by default. But afaik it should only activate when the browser is severely low on system resources. Therefore, I would say that having tabs discard automatically is  a much nicer user experience than chrome crashing or performing very badly due to low resources.

As @Diablo-D3 mentioned, this has nothing to do with this extension, and tab discarding cannot be turned off (except manually in chrome://flags). 

Also, you may be interested to know that I *have* made a version of the extension which uses chrome's discarding logic. It's called The Great Discarder (i know) and is available on gitHub here:
https://github.com/deanoemcke/thegreatdiscarder
and on the webstore here: https://chrome.google.com/webstore/detail/the-great-discarder/jlipbpadkjcklpeiajndiijbeieicbdh?hl=en

It's a complete rewrite of the extension, as utilizing tab discarding completely changes the way the extension needs to work. That said, the UI is identical, it's just missing a few features that no longer make sense.
