### ISSUE TITLE
Add "dont suspend this tab" button

### ISSUE THREAD

**Issue by iMakedonsky** [deanoemcke/thegreatsuspender#473]
Would be useful to have "don't suspend this tab" or "never suspend this specific url" button.

**Comment by deanoemcke** [comment]
There are already options for 'never suspend this site', and 'dont suspend for now'.
The first will add the root domain to the whitelist. The second will pause suspension of that specific tab until the page is either refreshed or the browser restarted.

If you specifically want an shortcut to whitelist a specific url instead of the domain, then refer to this issue: https://github.com/deanoemcke/thegreatsuspender/issues/321
