### ISSUE TITLE
Great suspender clone

### ISSUE THREAD

**Issue by bblokar** [deanoemcke/thegreatsuspender#500]
Is this somehow related to this extension?
https://chrome.google.com/webstore/detail/tab-memory-saver/pehgadfgejpbgkgkofomjkbgfbnhdfll?utm_source=chrome-app-launcher-info-dialog

Name is Tab memory saver, the whole interface and everything is exactly the same to the last dot... However, I use thegreattabsuspender and discarder, because I see 2 items you developed and I think another one is just a copy

**Comment by liamjohnston** [comment]
That other one is a copy. So lame :/

**Comment by nadams810** [comment]
I am not a lawyer, nor do I play one on TV, but it is perfectly acceptable to create "clones" under the GPL license. If you didn't want to allow this - then you should have chosen a more restrictive license.

However, it does appear this project is using GPL v3 and that project is using GPL v2 - which to my knowledge you cannot "downgrade" without express consent from the author. If the source is the same - I do believe the author would be well within their rights to file a DMCA take down (which is free and easy).

Paint .Net apparently used to be open source and was tired of malware writers making clones so they made it closed source. The funny part is that since it was written in .Net you can use a decomplier such as dotPeek to view the source anyways....

As an aside - I saw some of the comments - and really guys? Rating a project 1 star because it is a clone??? You do realize that plenty of projects throughout time are forks? Most popular - Ubuntu is technically a fork of Debian....

**Comment by piotrowski** [comment]
What is interesting about "Tab Memory Saver" is that Chrome Web Store says it has 4.1 million users, which is a lot more than the original extension. Is this data faked?

**Comment by liamjohnston** [comment]
Given the relatively low number of reviews, it'd say the data is somehow faked.

**Comment by eriknstr** [comment]
@nadams810 That project is using GPLv3 in their GitHub repo. https://github.com/KyongTsu/TabMemorySaver/blob/master/LICENSE. Where did you read that it's using GPLv2?

Totally agree with you on the point of rating a project 1 star because it's a clone. Being able to fork a project is a big part of the point of open source software.

**Comment by eriknstr** [comment]
@nadams810 It seems that you mixed up which one was which one when you were comparing licenses. It's thegreatsuspender that is GPLv2. https://github.com/deanoemcke/thegreatsuspender/blob/master/LICENSE. The GPLv2 allows publishing changes under the terms of GPLv2 or later, so the developer of tabmemorysaver is acting in accordance with GPLv2 in this regard when publishing their fork under GPLv3.

**Comment by brycenesbitt** [comment]
The question is are the clones adding value?  Are they forking for revenue purposes, or to improve things?  Are they feeding improvement back "upstream".
