### ISSUE TITLE
Who thought updating the extension while it being active is a good idea?

### ISSUE THREAD

**Issue by xaliber** [deanoemcke/thegreatsuspender#520]
I've just checked my browser and found I lost ALL of my 100-ish suspended tabs, leaving only one tab saying "The Great Suspender has been updated."

What the hell?!

**Comment by l-g** [comment]
"Me too". Nor can I find these tabs in the history.

**Comment by desertspringtime** [comment]
The tabs are in the extension's session management tab under options.

**Comment by RJVB** [comment]
"Me too".

In addition, I found that the extension had been disabled on 2 of my 3 systems (haven't checked the 3rd yet ) AND on the Mac there had apparently been a crash of the extension. That was actually what led me to the cause of the issue for I didn't get the "has been updated" window.

Oh, and Chrome/Mac claims that the extension has a severe known security issue?!

**Comment by TXC** [comment]
This is addressed in #512 and #513. Specifically this [comment](https://github.com/deanoemcke/thegreatsuspender/issues/512#issuecomment-306356434)

**Comment by xaliber** [comment]
Okay the tabs are in the tab history, kinda: chrome-extension://klbibkeccnjlkjkiokjodocebajanakg/history.html

Only tabs from two days prior though. Lost a number of other tabs. Oh well at least it's not a complete loss.

**Comment by handcraftedcomp** [comment]
Lost nearly all of my tabs too (except for last 4 opened) - created a Github account to specifically say I'm extremely unhappy about this. I can't see a way to disable the auto update, so I'm removing this extension.

**Comment by RJVB** [comment]
This happened because of an incident, not because it's part of the usual updating process.

Chrome does have a built-in "kludge" to do something comparable manually to what TGS does automatically:
- open the Task Manager
- select any of the processes corresponding to tabs that eat too much CPU or memory
- kill them with the "End Process" button

This will kill the process but not the tab. You can reload the tab manually when needed, and it will also be reloaded when you restart the browser.

**Comment by deanoemcke** [comment]
All comments regarding tab loss on update should be directed to issue: https://github.com/deanoemcke/thegreatsuspender/issues/163
