### ISSUE TITLE
each tab seems to have its' own copy of icon19(b) and chrome says they are uncacheable

### ISSUE THREAD

**Issue by ohsix** [deanoemcke/thegreatsuspender#535]
poking around in the dev tools while i'm suspending tabs in order to see why TGS stops responding at some point and noticed that Frames -> top -> Images gets a new copy of icon19/icon19b with each tab, icon19 is 164b and icon19b is 2.8kb

i don't know if these sum or anything, but when you have a lot of tabs you end up with a lot of copies

**Comment by deanoemcke** [comment]
Im unable to replicate this. Here is my version:
![image](https://user-images.githubusercontent.com/1051763/28583776-5ac3b0f8-7138-11e7-89a2-6e642968e392.png)

Can you confirm you are on v6.30?
And also, if you are having problems with the extension stopping responding, my first guess would be that it is related to the capturing of screenshots when a tab suspends?

**Comment by ohsix** [comment]
i'm on 6.30, i don't have page screenshots on

retracing my steps, it wasn't the popup, it was the background page

**Comment by ohsix** [comment]
![screenshot from 2017-07-31 15-02-20](https://user-images.githubusercontent.com/3180944/28800433-7a202328-7601-11e7-8cdd-b26adb9fbd39.png)
![screenshot from 2017-07-31 15-02-07](https://user-images.githubusercontent.com/3180944/28800428-74b14e76-7601-11e7-952b-a9fc221bc959.png)

**Comment by ohsix** [comment]
every time i pick /suspend all tabs' when there are tabs to suspend, the icon count goes up one

![screenshot from 2017-07-31 15-37-02](https://user-images.githubusercontent.com/3180944/28801389-29db18be-7606-11e7-928e-cf7108209b15.png)

an unrelated problem with my hard drive will have me busy for a while
thanks for looking, will check back when i can

**Comment by deanoemcke** [comment]
@ohsix finally got some time to look into this.
it turns out that this is just a failure of the chrome->application devtools tab to automatically refresh. if you close the background page and reopen it, you'll see there's only 1 instance of the icon19.png file.

the reason that these files stack up is because i update the popup extension icon depending on the currently viewed tabs status (it will go grey if the tab will not automatically suspend and turn yellow again when it will be automatically suspended). every time I call `browserAction.setIcon()` to update the icon, it adds a new resource to the 'Images' section pictured above.

**Comment by ohsix** [comment]
doh. thanks for looking

email filtering is burying my github notices :|
