### ISSUE TITLE
Support for OneTab 

### ISSUE THREAD

**Issue by barredo** [deanoemcke/thegreatsuspender#536]
Hi, I'm a heavy Great Suspender user, and I love using OneTab as well https://chrome.google.com/webstore/detail/onetab/chphlpgkkbolifaimnlloiipkdnihall

I'd like to know if there's a possibility of keep the suspended URLs in some way so OneTab can have access to them and use the extension to make groups (currently it can't because the suspended URLs are not final).

Thank you

**Comment by h3298** [comment]
Interesting.  OneTab looks really useful for systems with limited RAM.  Plus it helps to address a major flaw in Chrome (can't read tab titles due to shrinking tabs).  Also see this:

https://blog.mozilla.org/blog/2017/06/13/faster-better-firefox/
http://www.erahm.org/2017/05/15/firefox-memory-usage-with-multiple-content-processes/

https://addons.mozilla.org/en-US/firefox/addon/suspend-tab/
https://addons.mozilla.org/en-US/firefox/addon/tab-suspender-tab-unloader

**Comment by Omar-Elrefaei** [comment]
Yeah, this is annoying, I have also reported to Onetab to support favicons of suspended tabs.

**Comment by urfausto** [comment]
i'm giving this extension a try! it seems nice!

**Comment by deanoemcke** [comment]
Unfortunately I cannot do anything from my end to keep the original urls. They are already being recorded in the url via the &uri=xxx query parameter.
Other extensions (such as session buddy) seem to have built in support for The Great Suspender. OneTab would need to do the same.
