### ISSUE TITLE
Screen capturing does not work on pages with large tables

### ISSUE THREAD

**Issue by Pascal666** [deanoemcke/thegreatsuspender#554]
When a tab showing a large HTML table is suspended, no screen capture is made. 
 For example: http://giveawaylisting.com

**Comment by deanoemcke** [comment]
Yes. The package that I use to capture the screen can be quite processor intensive which to a certain extent defeats the purpose of the extension. To mitigate this, I prevent it from capturing screenshots of any pages with over 10000 elements.

This issue is somewhat related to: https://github.com/deanoemcke/thegreatsuspender/issues/503

**Comment by deanoemcke** [comment]
@Pascal666 As mentioned in #503 i have added a new preference 'Enable screen capture on zoomed tabs' which is disabled by default. This also has a hidden functionality that will override the 10000 element limit current imposed.
By enabling this preference, you will also be able to get image previews on tabs with large numbers of DOM elements.

**Comment by volt55** [comment]
@deanoemcke I have noticed that the screen capturing setting is automatically disabled for incognito mode windows whenever the browser is relaunched. Can you fix this? Did you know about this?

**Comment by deanoemcke** [comment]
@volt55 incognito mode does not have access to the settings from the extension in normal mode. in addition, it cannot save it's own settings (due to the nature of incognito).
The upcoming version has a settings sync feature (#262) which, when enabled, will allow incognito windows to sync the settings from the normal mode when the window is first created.

**Comment by deanoemcke** [comment]
In regards to the initial issue posted here, the fix has changed recently. I no longer do any filtering on the number of DOM elements. Instead, there is a timeout of 60 seconds when trying to render a screenshot. I have changed the 'zoomed tabs' feature to 'Enable high quality screen capture mode' which does a number of things, one of which is increase the timeout to 5 minutes.

For tabs with a lot of elements, whether it gets rendered will now depend on whether the render can be completed within this allotted time.

**Comment by Pictor13** [comment]
Sorry if I write here (didn't want to open a new issue just for that)..

I was wondering if the extension could have any influence on the [Offline Auto-Reload Mode](chrome://flags/#enable-offline-auto-reload) and allow to reload the page from cache, rather than resorting on a screenshot.

Screenshot is a viable solution for who doesn't want to keep a big cache, but as long as this is there would be nice to enforce the use of cache from TGS, without having to go messing manually in chrome://flags.

Although am not sure if that is feasible...

**Comment by deanoemcke** [comment]
@Pictor13 I briefly touch on this idea in this issue: https://github.com/deanoemcke/thegreatsuspender/issues/265

i don't think an extension can affect chrome flags at all.
and also, what are you wanting to achieve? part of 'suspending' a page is to remove the DOM which frees up memory. Loading a cached version of the page would not help in this regard. It would also not affect the javascript that tries to run.

the only real use-case i've considered for the offline-auto-reload mode is when you are indeed offline and want to access a website that has been suspended..

**Comment by Pictor13** [comment]
Nope, you are totally right.
Sorry I wasted your time to save mine, I mislead it because I didn't really try the screenshot functionality previously; after trying, I see its use.

About enabling the cache flag was more to ease the Great Suspender experience when offline.
But I thought that an extension would have no permissions for it; and handling it isn't a direct responsibility of TGS too.
