### ISSUE TITLE
Chrome Hangs Even After TGS Has Been Disabled

### ISSUE THREAD

**Issue by PMH232** [deanoemcke/thegreatsuspender#563]
(I don't know whether this issue has been reported yet; I don't have time to look through 262 Issues.)
(I was going to say "Removed" above - but, checking, I ssee that I had only disabled it.)

Ever since Disabling TGS, I've had Chrome become "not responding" at seemingly random times.
- with Task Manager taking up a huge %age of the CPU.

Sometimes, Chrome will manage to recover from this, if given enough time; sometimes, who knows?

Restarting at least gets Chrome to work again for a little while.

I just uninstalled, and then re-installed Chhrome, & that seems to have fixed it.

(Maybe just trashing TGS would've fixed it,too.)

(I didn't lose my Bookmarks or History, as I was afraid I would.)

This tells me that TGS leaves something ~in~ Chrome after it has been disabled!

That's reprehensible - and I again call for this kind of irresponsible developer behvior to be kept out of the Chrome Store.
How many man-hours has been wated by TGS???

**Comment by deanoemcke** [comment]
Im sorry but I do not agree with your conclusions. If you have the extension disabled, then it will not be actively affecting your chrome in any way. Do you think it could be possible that it is precisely BECAUSE you have disabled then extension that your chrome is suffering from performance issues?
The whole point of this extension after all, is to reduce the memory and cpu consumption of chrome.

If you really want to test your theory, then you could at least compare the disabled state of the extension to the completely removed (uninstalled) state. If you uninstall the extension, absolutely everything about the extension is removed from your chrome. This is the only valid way to perform a comparison. Reinstalling chrome itself will not provide you with a fair test.

**Comment by PMH232** [comment]
>Im sorry but I do not agree with your conclusions. 
>If you have the extension disabled, then it will not be actively affecting your chrome in any way. 
>Do you think it could be possible that it is precisely BECAUSE you have disabled then extension that your chrome is suffering from performance issues?

No.  I'm not experiencing performance issues; what I'm experiencing is Chrome Not Responding - for an unkown (but way long) amount ot time - and with very few (eg: 1) tabs open.

> The whole point of this extension after all, is to reduce the memory and cpu consumption of chrome.

> If you really want to test your theory, then you could at least compare the  disabled state of the extension to the completely removed (uninstalled) state. 

I don't know the detaile of Chrome's state model, but I'd be very shocked if a Disabled Extension is alowed to have anything to do with Chrome's behavior.
Assuming so, what's the diff betw/ Disabled and Removed/Uninstalled?

>If you uninstall the extension, absolutely everything about the extension is removed from your chrome.

...whereas, if it's only Disabled, what?


>This is the only valid way to perform a comparison. 

Why?


>Reinstalling chrome itself will not provide you with a fair test.

Maybe -- although Why? -especially, considering the above

If reinstalling Chrome fixes everythng thst TGS has bleeped up, then I'm cool with that, regardless of whether/not it reveals all the probems of TGS.

If it doesn't, then TGS(*) is screwing up stuff even outside of Chrome.
(*:  or something else, of course -- which I don't think is the case.)
(OTOH, Restarting isn't able to get Chromw back to running Not-Responding--free.  I'm blaming TGS  for screwing-up something in Chrome's "default"(?) files.)

**Comment by deanoemcke** [comment]
I'm not sure of the exact difference between a disabled extension and a removed one in regards to a running chrome. Possibly there is no difference (which is what i would expect).

However, if you reenable a disabled extension, it still has all of the saved extension preferences and associated data. Whereas if you remove the extension this all gets permanently deleted.

I'm sceptical of your assumption that the extension is causing your 'chrome not responding' issues, purely because i doubt a disabled extension can have any effect on a running chrome.

I was merely suggesting that you repeat your tests after completely uninstalling the extension just to be sure. You seem to be under the impression that the extension is causing you issues even when disabled, so I'm suggesting remove it and see if it still gives you issues.

AFAIK it is impossible for an extension to do anything with chrome's default files. And equally impossible that it can affect your chrome after it has been uninstalled. And most probably impossible that it can affect your chrome while it is disabled.

Sorry if my initial response was vague. I hope this clears up what I was trying to say.

**Comment by PMH232** [comment]
Thank you for your email.

I'm going to have to have Geek Squad take a look.  What you say makes
sense, but my experience was what it was.

I'm still getting ~hangs~ every now & then.  The frequency seems to be
decreasing slowly.  Which sounds crazy -- but ...

I do wish I could use TGS; it was great absent all these problems (and the
fact that it doesn't save the state of Suspended Tabs.
