### ISSUE TITLE
"Unsuspend all tabs" should reset suspend timer on all tabs

### ISSUE THREAD

**Issue by janpio** [deanoemcke/thegreatsuspender#571]
Right now I often use "Unsuspend all tabs" to get all my tabs active again. But when I go through them, some of the tabs are still suspended. 

First I thought the extension wouldn't unsuspend them, but this doesn't seem to be the case. Is it possible that the timer of the tabs is not reset when I hit that button, so it is possible that 2 min after I unsuspended all these tabs are suspended because I last interacted with them an hour ago?

**Comment by deanoemcke** [comment]
The suspend timer for each tab is reset when the page loads. So it's much more likely that the suspended tabs you encounter were never unsuspended in the first place.

> First I thought the extension wouldn't unsuspend them, but this doesn't seem to be the case.

Can you please explain why **this doesn't seem to be the case**?
And is there a reason you use 2 minutes in your example above? Or are you just using that number as a 'for instance' ?

It would be good if we could confirm whether these tabs unsuspend and then resuspend, or whether they just never unsuspend in the first place. If you have few enough tabs in a window so that you can see all the favicons of each tab, then it should be fairly easy to confirm whether all the tabs unsuspend correctly, as all their favicons will change from being faded-out to being full colour.

Are you able to perform that test for me?

**Comment by janpio** [comment]
> Can you please explain why this doesn't seem to be the case?

I think (! - not sure anymore...) after I noticed this problem (suspended tabs although I did "Unsuspend all tabs" and the "automatically suspend after ..." timeframe is not yet use up again) I saw all my tabs as active. Short time later some of those were suspended when I tabbed to them though.

> And is there a reason you use 2 minutes in your example above? Or are you just using that number as a 'for instance' ?

Sorry, that was indeed just a random number for "short time frame".

Should the right now unsuspended tabs get their unsuspend timer reset when I use "Unsuspend all tabs"? Or should they indeed be suspended 2 minutes after I "Unsuspend all tabs" if they were 2 minutes from being suspended?

**Comment by deanoemcke** [comment]
Any tabs that were suspended when you click 'unsuspend all tabs' should get unsuspended and have their timers reset to the full amount. Any tabs that are not yet suspended will not be affected, so if they are quite close to suspending then they will suspend more quickly than the newly unsuspended ones. 

In writing this reply, I think I have just grasped what you are trying to request. 
Are you suggesting that those tabs *not* suspended should also have their timers reset back to full when you click 'unsuspend all tabs' ?

**Comment by janpio** [comment]
Yes :)

That was what I naively expected... 
Because with the current behaviour a tab can be suspended until I get to it after using "unsuspend all tabs" which feels broken.
