### ISSUE TITLE
"Open link in new suspended tab" just clones the current page

### ISSUE THREAD

**Issue by baz357** [deanoemcke/thegreatsuspender#572]
"Open link in new suspended tab" sounds like a great option, but it just opens the *current* page in a new suspended tab, not the link I use it on.

I'm using the latest Chrome version.

**Comment by deanoemcke** [comment]
This feature is being removed in the upcoming version. It will be replaced with a new option: Instantly suspend tabs created with 'Open Link in New Tab'

This can be enabled globally and will cause all new tabs opened to be suspended as soon as they load.

**Comment by baz357** [comment]
Hmmmm.... that alternative sounds less flexible, but maybe it'll be just fine. :)

Can you share when the new version will be ready?

**Comment by deanoemcke** [comment]
@baz357 the new version will be out within the next two weeks (failing any catastrophe in the test build).

I decided to change from a right-click 'open in new suspended tab' to making it a permanent option for two reasons:
1) If the user has the right-click context menu enabled, then the 'open in new suspended tab' option becomes hard to navigate to as you need to go through the 'The Great Suspender' sub-menu to access it.
2) Users that use (ctrl/command)+click to open links in a new tab will be able to use this feature now as it doesn't depend on a context menu mouse click.

It's also worth noting that in the upcoming release, I have changed the way this feature works. In the previous version, it would truly open in a new suspend tab. The problem was, that if this url had never been loaded before, the extension would have no way to know what the favicon and page title should be. This led to a rather buggy experience (as you have noted).

The new implementation actually loads the page first, and once it's fully loaded, it then suspends it. This gives it access to the page favicon, title, and also screen capture - however it does mean that pages will still have to load first.

**Comment by baz357** [comment]
So... will there still be a way to open tabs unsuspended, maybe with the middle mouse button? I imagine auto-suspending *all* new tabs could be a bit annoying for casual browsing.

Or will there be a second "don't auto-suspend when opening, but after x minutes" whitelist?

**Comment by deanoemcke** [comment]
I have backtracked on this. And reintroduced the right-click 'open in new suspended tab' option.
With two improvements to the current implementation:
- As mentioned above, it now actually loads the page and the suspends it.
- The rest of the right-click context menu will not appear when right clicking on a link

**Comment by baz357** [comment]
Thanks, I like the new version! :)

What exactly does "Don't suspend for now" do, how long is "for now"? Will it not suspend the tab until Chrome is restarted?

**Comment by liamjohnston** [comment]
@baz357 Think of it as "whitelist for this session" (which could be a better label...). I use it a lot, great addition :)

**Comment by baz357** [comment]
Ah, ok, thanks for letting me know. Yes, I can imagine that being helpful at times.

**Comment by baz357** [comment]
@deanoemcke: regarding "As mentioned above, it now actually loads the page and the suspends it", I'm requesting a small change. I tested the feature on several sites, and it's so fast that the new suspended tabs end up with the respective **site's** name displayed as the tab's title, not - as I expected and what I would prefer - the actual **page** title (like when I manually suspend a page). That results in half a dozen suspended tabs, all with the same title.

I don't know if others would prefer this too, so maybe make it optional? ("Delayed suspending [wait for page title]")

**Comment by deanoemcke** [comment]
@baz357 It sounds like you might still be on v6.30 of the extension. That version does not have the *new* 'open in new suspended tab' functionality.

The version on the webstore right now is not the most recent version. The most recent version can only be installed by downloading the source from gitHub. See the 'Install as an extension from source' on the README page of this project for instructions on how to try this new version.

Or alternatively, wait until the new version is released to the webstore which will be soon.

Apologies if you really are running the code from gitHub source. If so, can you please confirm the version you have running? I am unable to replicate your issue here.

**Comment by baz357** [comment]
You're right, I'm still on 6.30. I had expected to be on the new version since the 'open in new suspended tab' behavior is different (better) than in August, when I started this thread.

I'll wait until the new version is released to the webstore.

**Comment by baz357** [comment]
> Or alternatively, wait until the new version is released to the webstore which will be soon.

6 weeks have passed and still I have to cry myself to sleep every night because I still have to make do with 6.30. Please push the new version to the webstore. :)
