### ISSUE TITLE
Bug: that awkard moment after clicking 'save' (session)

### ISSUE THREAD

**Issue by urfausto** [deanoemcke/thegreatsuspender#586]
When you save a session you must reload the page to see if it actually got saved, it never appears once you have clicked the save button.

**Comment by deanoemcke** [comment]
I dont understand. Once you click save, it should prompt you for a name. Once you've entered a name, a new entry with that name should appear under the 'saved sessions' section.

There should be no need to reload the page. Unless you're referring to the situation where a session of that name already exists?

**Comment by urfausto** [comment]
nope, i need to reload in order to view the saved session.
my specs: windows 7 x64bit, vivaldi browser x64bit.

**Comment by Pascal666** [comment]
I see the same behavior on v6.30 on Chrome.  The new entry only shows up under the 'Saved sessions' section after you reload the Session management tab or leave it and come back.

**Comment by deanoemcke** [comment]
@urfausto @Pascal666 could you please open chrome developer tools when on the session management page, and see if you get any console errors after clicking the save button?
I'm assuming you are both seeing the 'Enter a name for this session' popup?

**Comment by Pascal666** [comment]
No errors on the console.  Yes, the popup shows, and the session gets saved successfully, it just doesn't show up in the saved list until after the page is reloaded.

**Comment by deanoemcke** [comment]
OK. Thanks.
On closer look at the code of v6.30 it looks like there's a race condition between the session saving and the page updating. You must have a faster computer than me!

This has been resolved in the upcoming release (v7.x)

**Comment by Pascal666** [comment]
Thank you.  Perhaps my sessions are larger than yours and thus take longer to save?  My current session is 220 windows, 795 tabs.

**Comment by deanoemcke** [comment]
@Pascal666 oh yeah. that would do it!
far out. that's a lot of tabs and windows! 
out of curiosity, why do you have so many windows? 795 tabs i can (almost) imagine. But 220 windows? Why so many? And how do you navigate between them?

**Comment by Pascal666** [comment]
I work on multiple projects and group related windows together.  In addition to the Chrome windows, I have an about equal number of other program windows, mainly PuTTY, Notepad, Excel, and DOS Prompt.  I have multiple taskbars I scroll up and down through.  I use 7+ Taskbar Tweaker to allow me to drag n drop windows around on the taskbars to group them appropriately.  Each project uses a different number of each application, so I can often scroll through taskbars until I see the right one (three PuTTY windows in a row, or two DOS Prompts separated by two Chrome windows, etc).  I also use the Chrome extension Quick Tabs so I can quickly flip to recent tabs and search tabs by title text.  I reboot about once a month, usually shortly after patch Tuesday, because it takes me a while to get all my programs running again and grouped correctly.
