### ISSUE TITLE
Auto-suspend tabs that are about to be discarded

### ISSUE THREAD

**Issue by Pascal666** [deanoemcke/thegreatsuspender#596]
If Chrome discards a tab before The Great Suspender's inactivity timer suspends it, the tab will not be suspended.

Can The Great Suspender set chrome://flags/#automatic-tab-discarding to disabled during install?

Or trap when Chrome is about to discard a tab and suspend it instead?

**Comment by deanoemcke** [comment]
Yes, I am aware of this issue. It's not that bad, considering that discarding a tab is fairly equivalent (or maybe even better) than suspending a tab memory-wise.

Unfortunately an extension cannot interact with chrome flags.
But it does look like I can detect when a tab is discarded, at least, *after* a tab has been discarded. I could then reload and suspend it.

I'll make this a feature request.

**Comment by Pascal666** [comment]
In my experience, tab discarding does not save nearly as much memory as TGS.  Could be plugin related.

**Comment by deanoemcke** [comment]
This has been implemented in the upcoming release.
The option actually reads "Instantly suspend when system memory gets very low"
but it does exactly as requested. When a tab gets discarded (ie: because the system memory has gotten really low), then it will undiscard it and suspend it instead.

The main motivator for implementing this was so that I can still interact with the tab (for functionality like 'unsuspend all'). With discarded tab, it also prevents communication via content scripts.

**Comment by johnkershaw** [comment]
This may not be working 'as advertised/intended'. 

I'm getting tabs suspended ALL the time, even immediately after loading. I have TGS set to suspend after 1 hour. Seems like it's triggering pre-discard suspension when the conditions wouldn't otherwise kick in.

I can open a tab, load a site, switch to another tab, switch back, and TGS has suspended it. Click to reload... now the other tab has been suspended. 

I generally have 20-30 tabs open, but have previously had WAY more open without problems (from Chrome itself or TGS).

Chromebook CB3-431 with only 4Gb memory, been using TGS for (years?)

**Comment by johnkershaw** [comment]
I've now unticked the 'instant suspend' box and will let you know if it helps. 

Happy to assist with debugging if useful :)

**Comment by deanoemcke** [comment]
@johnkershaw thanks for the feedback. i'm hoping that this is simply a case of tabs being suspended after they discard. it does seem odd that it's happening so frequently though.

we can see for sure what is happening if you turn debugging on and give me a copy of the log after it happens. 
to turn on debugging, open the extension options page, and then change the word 'options.htlm' in the url to 'debug.html' 
once on the debugging tab, you can toggle error and info logging on at the top of the page.
