### ISSUE TITLE
Active tabs in passive windows are not auto-suspended

### ISSUE THREAD

**Issue by barbushin** [deanoemcke/thegreatsuspender#614]
How to reproduce
1. Set auto-suspend delay to 20 seconds
2. Open multiple Chrome windows (instances)
3. Work in one window for 20 seconds
4. Open another window, you'll see that tab is not suspended

Looks like The Great Suspender detects active tab as tab opened in Chome Window. But it must be also the rule that window is active or not. It's very critical for people who use multiple workspaces or prefer to use different Chrome windows for different topics.

**Comment by deanoemcke** [comment]
Thats correct. This was by design. Although at the time I never imagined that people may have over 100 different windows open.
I thought that it would be nice to always have the active tab of each window unsuspended, but in the case of 100 windows, it would probably be preferable to have these suspend.
I will try to address this issue soon.

**Comment by barbushin** [comment]
@deanoemcke Not 100, but even 5 opened windows could be a problem if one of this windows has high CPU load.

**Comment by ProditorMagnus** [comment]
I rely on current behavior. Would be nice to keep such option.

**Comment by taniadaniela** [comment]
There could be an option that disables having the active tab of each window unsuspended when there's only one tab, by default it could keep the current behavior.

**Comment by deanoemcke** [comment]
This has been implemented and will be available in the next release.
