### ISSUE TITLE
[Alpha] No unsuspend option in menu?

### ISSUE THREAD

**Issue by fwextensions** [deanoemcke/thegreatsuspender#626]
I can finally suspend Enterprise Gdocs again!  But when I click the icon on a tab suspended by the alpha version, there's no unsuspend option in the menu:

![image](https://user-images.githubusercontent.com/61631/33465942-978ad21a-d5ff-11e7-9d0c-42da302e002c.png)

Compared to webstore version:

![image](https://user-images.githubusercontent.com/61631/33466010-fe2fa414-d5ff-11e7-908a-1ac0d5a53e8e.png)

Is that intentional?  Also, the icon is greyed out (maybe indicating a dev version?).

A suggestion for when the content scripts don't load: maybe just say "Auto-suspend is unavailable", with a link to more info.  Saying "Failed to load tab information" might sound overly concerning to some users.  

It would also be nice if the timeout on trying to contact the content scripts was shorter.  It will never work on these pages, so I need to wait each time I want to suspend one.  (Then again, the shortcut seems to work right away, so I guess I should just use that.)

**Comment by liamjohnston** [comment]
@fwextensions The lack of an 'Unsuspend' option is intentional. We didn't think anyone would try to unsuspend via the popup given you can click anywhere on the suspended tab to do it (or set a keyboard shortcut, or refresh the tab).

A grey icon means that the current tab will not suspend for some reason. There are lots of possible reasons, including:
- it's already suspended
- it's whitelisted
- it's receiving form input
- it's a 'chrome' tab (not sure what these are better known as, sorry), e.g. TGS settings page, Chrome preferences tab, downlaods tab (chrome://downloads/) etc.

There's a known bug where sometimes if you open a tab that can't be suspended, the TGS icon is coloured, and only changes to grey if you switch tabs then switch back.

**Comment by fwextensions** [comment]
Yeah, I guess I only noticed because I was comparing the menus between the webstore and alpha versions.  Closing this since it's intentional.

**Comment by deanoemcke** [comment]
@fwextensions just a couple more things.
the 'timeout' trying to contact the extension is actually just waiting for the tab to load (plus about 1 second after as the actual timeout).
once the tab has loaded, i can then test for the content script. so it only takes a long time on tabs which take a long time to finish loading. 

I like your suggestions for the improved wording. I have made the changes :)
https://github.com/deanoemcke/thegreatsuspender/commit/567448943d089b0d46a3eb5950f3358b6100f09b
