### ISSUE TITLE
Chrome shortcuts possibly disabled by this extension

### ISSUE THREAD

**Issue by mrpotatoes** [deanoemcke/thegreatsuspender#633]
I'm using `Shortkeys (Custom Keyboard Shortcuts)` alongside this extension. It seems that I cannot use my shortcut for "previous tab" and "next tab" in chrome. I think this extension may be halting that behavior.

Extension in question that adds next & previous tab keyboard naviation: https://chrome.google.com/webstore/detail/shortkeys-custom-keyboard/logpjaacgmcbpdkdchjiaagddngobkck

**Comment by deanoemcke** [comment]
Unfortunately this is unavoidable. It is due to the way that tabs are suspended. They redirect to a local page that is hosted by the extension, and these local pages cannot accept keyboard shortcuts from other extensions.

This issue has been discussed in more detail here: https://github.com/deanoemcke/thegreatsuspender/issues/271
