### ISSUE TITLE
Suspend tabs in minimized windows [Feature]

### ISSUE THREAD

**Issue by kuwaitbinary** [deanoemcke/thegreatsuspender#662]
Hi it would be helpful if there is a feature to **automatically suspend tabs in minimized windows** thank you.

**Comment by deanoemcke** [comment]
This should already be the case. I have tested this and it works as expected. If I minimise a window with many tabs, and then wait for the defined automatic suspension time, and then unminimise the window, all tabs except the active one are now visible.

**Comment by ossilator** [comment]
there is no contradiction from the OP, but i'd have interpreted this request differently: add an option to suspend tabs _only_ in minimized windows. that would make it easy to manually maintain a two-level working set (window switch due to (short) interruption vs. minimization because of (major) postponing). that's kinda one level up from #818.
