### ISSUE TITLE
Update scroll position when scrolling on suspended tab

### ISSUE THREAD

**Issue by wowkin2** [deanoemcke/thegreatsuspender#663]
When the tab is suspended and the only screenshot of the whole page is shown, I scrolled down and want to click on something, but it reloads the page and set scroll position to the most top.
Propose to set `scrollAfterReload = scrollBeforeReload - #('gsTopBar').height`

**Comment by deanoemcke** [comment]
An interesting idea. Currently, it remembers the scroll position of the unsuspended tab, and then will set the scroll position of the screen capture to the same position. And also set the tab back to this position once unsuspended.

But you're suggesting that if you change that scroll position by scrolling the screen capture, this new position should be used when unsuspending rather than the original scroll position before suspension.

I'm curious to know if you were aware of the current functionality that i described above. Do you think that your implementation is more intuitive?

**Comment by wowkin2** [comment]
@deanoemcke, I didn't know about existing functionality, at least it doesn't work for me on `Chrome v64.0.3282.186` and `The Great Suspender v6.30`.
Perhaps, because I use option `Capture entire page`. Can that be a reason? Should I use only `Capture visible screen only`?

**Comment by rickhg12hs** [comment]
Would it be possible (through an extension-wide option or default) to also store/recall the scroll position of tabs even when there is no screen capture?  Sometimes I'm reading very long documentation pages and it would be nice if they were restored to my last position when I finally get back to reading them.

**Comment by liamjohnston** [comment]
@rickhg12hs The latest `master` version can do this. So either hang out for the next webstore release (not sure when this will be.... hopefully soon) or install the latest master from source. 

Instructions here: https://github.com/deanoemcke/thegreatsuspender#install-as-an-extension-from-source

Make sure you unsuspend tabs before disabling whatever version you currently use! Or they'll be lost.

**Comment by rickhg12hs** [comment]
@liamjohnston Cool!  Thanks!

**Comment by deanoemcke** [comment]
Yes, there is a bug in v6.30 where the remembering of scroll position doesn't work: https://github.com/deanoemcke/thegreatsuspender/issues/592

As @liamjohnston said, on unsuspend, the tab will return to the scroll position it was at _before_ the tab was suspended.

This works no matter what options you have set for screen capturing. Although if you do have screen capturing set to 'Capture entire page' then it will also scroll to that location on the screen capture as well.
