### ISSUE TITLE
Improvement: Show message when adding XX to whitelist successful on suspended tab

### ISSUE THREAD

**Issue by yxliang01** [deanoemcke/thegreatsuspender#668]
I think it will be better if there is some kind of toaster or message showing that adding to whitelist is successful, instead of just clicking and nothing seems to happen (we don't know whether adding to whitelist is successful until checking the setting tab, although it is supposed to be always successful). I think this can improve user experience.

Thanks

**Comment by deanoemcke** [comment]
there is some form of feedback already.
after you whitelist, the suspended tab should reload.
and if you look at the extension icon, it should now be grey instead of orange which indicates that this tab will NOT be suspended automatically.

if you click on the icon the popup will give you extra feedback (see image):

![image](https://user-images.githubusercontent.com/1051763/37537002-a227c0ae-2922-11e8-9080-329f27c3538d.png)
