### ISSUE TITLE
Thoughts on option to automatically suspend tabs that open in background?

### ISSUE THREAD

**Issue by orschiro** [deanoemcke/thegreatsuspender#683]
Dear @deanoemcke and others, 

Let me picture my use case. I have a bookmark folder called "daily" that I open, well, on a daily basis. :-D

I treat it like my working session. It contains a bunch of tabs and I don't need all to open actively. 

That said, a feature for the suspender to automatically suspend tabs that open in background would be really neat!

Whenever I open those dozen tabs, my Chrome slows down a lot. It doesn't crash but, well, the experience is not that great. 

Am I alone with this use case or do more people find this interesting? :-)

Thanks!

**Comment by deanoemcke** [comment]
There's a bit of history already to this request.

Firstly, there is already a feature where you can right click on a link and choose 'open link in new suspended tab'. In the latest version (unreleased) this will full load the site in a new background tab, and once it has finished loading, it will suspend it. There is already an issue related to this feature: https://github.com/deanoemcke/thegreatsuspender/issues/572

It does this (the loading first) because otherwise there would be no way to find out the correct page title and favicon for the site. If I simply opened the link in a new **already** suspended tab, then the suspended tab would have no favicon or page title. This is pretty unusable. There are exceptions to this. If the site has already been suspended recently, then it's possible that I could reuse the favicon and page title. But this is not guaranteed, so I made the decision to not allow it at all.

There is also another issue already in existence which requests that **all tabs** that are opened in a background tab should be suspended automatically. This is to avoid having go through the right click context menu (ie. when using ctrl+click to open a link): https://github.com/deanoemcke/thegreatsuspender/issues/655
This is perhaps what you mean when you say "a feature for the suspender to automatically suspend tabs that open in background".

And finally, your request which seems to be the ability to open a whole session as already suspended tabs. I have a few questions about that, and some potential solutions.

1. How are you currently re-opening your 'daily' tabs? Using another session manager extension? Or perhaps with chromes 'reopen where i left off' ?

2. Depend on your answer to question 1, you might find that what you're after already exists. If you restore a session and some of those tabs are suspended in that session, then when you reload the session they will reload as already suspended.

3. Are you aware that The Great Suspender has a session management feature? If you go to settings -> session management. From there you can save sessions (like your daily session), and you can also choose to reopen a session with 'resuspend' which will open all the tabs in that session as suspended.

Hope that helps. Let me know.

**Comment by orschiro** [comment]
@deanoemcke! :-)

Thanks so much for your extensive reply. I think we are onto the right track here and I may have to try your session feature. 

Check this video to see how I open my daily tabs: 

https://www.useloom.com/share/499306fbe32044df8b951484383dae9e

And then you will probably understand that this is a horrible experience. Dozens of tabs opening at the same time and loading the content. My Chrome freezes from time to time!

Is there any solution to it? Actually, I think that Chrome natively should open tabs in batches instead of all at once...

What do you think?

**Comment by deanoemcke** [comment]
Chrome does do some batching. As in, it will progressively load the tabs. But it still generally uses 100% CPU.

Once you've loaded all your bookmarks, you should be able to save those tabs as a session in the session manager of The Great Suspender.

Then in future you should be able to reload the session from there rather than bookmarks.
But to be honest, the session manager in this extension is not the best. You're probably better off using an extension like Session Buddy. If the session you have in session buddy has already suspended tabs, they will reopen as suspended.
