### ISSUE TITLE
Questions on Great Suspender functionality. 

### ISSUE THREAD

**Issue by Protonus** [deanoemcke/thegreatsuspender#707]
Hi!  First of all thank you for your great plugin, been really enjoying it for about a year now. 

I recently have been having an issue where Chrome seems to be causing my computer to run out of virtual memory - which then leads to extreme system instability, crashing services, etc.  I've done all manner of playing with the page file settings,- it was originally windows managed, and I even gave myself as much as 32 GB of page file at one point (my workstation has 32 GB of RAM).  This seems to largely happen when I'm NOT at work, hours after I've left, I'll get messages in my Windows System Event Log, that say "Windows successfully diagnosed a low virtual memory condition. " and it names Chrome as every application that's to blame.   What's odd is that my page file or physical memory never seem to actually be low or saturated. 

This makes me think that it's tab suspension that may be causing this?  I run the latest development builds of Chrome - Chrome Canary, in Windows 10.  I'm currently running build 70.0.3510.2.  I recently found out that Chrome themselves have introduced a feature that's very similar to yours - called Tab Discarding?    I found that Chrome had the flag for it set to "default" - and I saw posts from about 2 years ago that say that for Canary, it was on by default.  I have now set it to Disabled.  I hope this helps, but too soon to say.

I'm curious, if this feature interferes, or interacts poorly with your extension?  Or if your extension over writes it?  Or if I'm better off using Chrome's discard feature over your extension now?  I was really hoping for your feedback on this as I'm sure you're probably the best person to ask! 

One other thing I wanted to ask about is your Session Management feature. I never noticed the options for it before today.  Does this work like Session Buddy - allowing me to restore a chrome session state?  Does yours only restore the tabs that have been suspended?  Or would it restore all tabs / pinned tabs as well?  Any information about what this feature can provide would be great.

Thank you so much in advance!

**Comment by fwextensions** [comment]
I've been running the alpha TGS with tab discarding enabled in Chrome 67 on a Win7 machine with only 8GB and a few hundred tabs open (many suspended) and haven't noticed any low virtual memory warnings.  I've left the discarding enabled for testing, even though it seems to be quite stupid in what it chooses to discard.  I'll often open a new tab with a lot of content (like a long Google Doc) and then go back to the previous one, only to find it reloading because it was discarded, despite having been using it seconds ago.

**Comment by UZR2000** [comment]
Please add a keyboard shortcut to "suspend other tabs"

**Comment by deanoemcke** [comment]
@Protonus 

In regards to the session management feature. Yes, it is very similar to session buddy. Although if you really want a decent session manager, I would recommend using session buddy over the great suspender. The session management feature was mainly developed to help users recover lost tabs during an extension update.

For the tab discarding, it is in chrome stable now. But only gets activated by chrome under severe memory pressure. In that way it operates differently to TGS. Even with tab discarding, chrome will happily eat up 8GB of ram, so long as it's available to be consumed.
I actually have another extension called The Great Discarder, which uses the native chrome discarding instead of the suspending that TGS uses. You might want to try that? Although it's not maintained like TGS is.
And actually, in the upcoming release, I have actually made some hidden flags that will allow you to use tab discarding in TGS instead of tab suspension. This will not be available from the general options screen though. It can only be accessed from the debug screen.

As for the memory / performance issues you're encountering, perhaps it would be best to create a seperate gitHub issue for this.
Alternatively, here is a generic issue I created where people can post their memory usage stats: https://github.com/deanoemcke/thegreatsuspender/issues/613
