### ISSUE TITLE
Whitelist is lost when the extension updates

### ISSUE THREAD

**Issue by saurabhgayali** [deanoemcke/thegreatsuspender#740]
Issue:
An automatic update causes loss of whitelist. I took much time to update the whitelist according to my usage and chrome automatically updated the extension. If the github version is more advanced to be free from this bug why a bugged version is launched in chrome webstore. Chrome automatically updates extension without asking and this will happen again next time the extension is updated. I just want to make sure that this doen't happen next time. 

There is no option even to export and import whitelist manually. 

### Specifications:
 * Extension version: v7.0.109
 * Browser & version: Google Chrome Version 68.0.3440.106 (Official Build) (64-bit)
 * Operating system & version: Windows 7 (64bit)

**Comment by SnIPeRSnIPeR** [comment]
Me too

**Comment by deanoemcke** [comment]
@saurabhgayali @SnIPeRSnIPeR can you guys confirm whether the new 'Sync settings between different systems' option is turned off or on? And also whether you have manually changed this setting?

@saurabhgayali during testing i had no problem with the whitelist during update. also, the next update will warn you before it updates, giving you a change to backup your suspended tabs. for the whitelist, you could easily back that up just by saving a copy of the text manually, or if you do enable options synching, then it will be automatically backed up to your chrome profile.

**Comment by SnIPeRSnIPeR** [comment]
Turned on, but I dom't have different system..

![2018-08-28_12-13-29](https://user-images.githubusercontent.com/31162059/44702085-d2615300-aabb-11e8-9cf1-535cb8214760.png)

![2018-08-28_12-13-34](https://user-images.githubusercontent.com/31162059/44702087-d5f4da00-aabb-11e8-929e-34ba87b5f1b9.png)

**Comment by deanoemcke** [comment]
@SnIPeRSnIPeR @saurabhgayali 
the reason i ask about the settings sync option is because there is some special behaviour around whether that is on or off. 

people upgrading from an older version should have that setting defaulting to OFF. so it's weird that it's ON for @SnIPeRSnIPeR if you haven't touched it.

if you install for the first time, then that setting should default to ON, and should prevent against loss of settings in the future.

The reason it defaults to OFF for existing users is to protect users that have different whitelists on different computers (but on the same chrome profile). As soon as you turn syncing on, it will overwrite the options of all other computers logged into the same chrome profile that also have the settings sync option on.

@saurabhgayali could you tell me whether this option was ON or OFF for you?

I would like to investigate whether there is an issue with the code that determines the above behaviour.

**Comment by saurabhgayali** [comment]
> @SnIPeRSnIPeR @saurabhgayali
> the reason i ask about the settings sync option is because there is some special behaviour around whether that is on or off.
> 
> people upgrading from an older version should have that setting defaulting to OFF. so it's weird that it's ON for @SnIPeRSnIPeR if you haven't touched it.
> 
> if you install for the first time, then that setting should default to ON, and should prevent against loss of settings in the future.
> 
> The reason it defaults to OFF for existing users is to protect users that have different whitelists on different computers (but on the same chrome profile). As soon as you turn syncing on, it will overwrite the options of all other computers logged into the same chrome profile that also have the settings sync option on.
> 
> @saurabhgayali could you tell me whether this option was ON or OFF for you?
> 
> I would like to investigate whether there is an issue with the code that determines the above behaviour.

The options where whatever is default. and this wasn't an option in older version.

**Comment by cdick001** [comment]
I have the same problem after update.
The whitelist is still there, it recognize that the site is added to the whitelist, but it just ignore it and still suspended the site.

**Comment by deanoemcke** [comment]
@cdick001 your issue sounds different. this issue is for people losing their whitelist. most probably you  are suffering from this other issue: https://github.com/deanoemcke/thegreatsuspender/issues/723
