### ISSUE TITLE
Can't unsuspend the tab after a while around the "square face"

### ISSUE THREAD

**Issue by Anthrwpos** [deanoemcke/thegreatsuspender#753]
Why with new design, the tab after a while, can't unsuspend it anywhere in the page but only in square face that sleeping? I mean isn't  clickable around the "face" when the page is suspendet. Or it's only from me?

### Specifications:
 * Extension version: 7
 * Browser & version: Opera, 54.0.2952.60
 * Operating system & version: Win. 8.1, 64 bit.

**EDIT**: It's possible for now to have the old version? (4.61)

**Comment by liamjohnston** [comment]
It's probably an opera thing. It hasn't really been thoroughly tested outside of chrome (firefox a little bit). Making it officially compatible with other browsers is a feature that is likely to come at some stage though, and this clickability issue would be addressed.

**Comment by Anthrwpos** [comment]
Ok. You know if it's possible to have the oldest version of this extension? (4.61)

**Comment by deanoemcke** [comment]
@Anthrwpos can you please take a screenshot of one of the pages that is not working for you? That might help me work out what the issue is.
I have tried waiting over a day on opera with a suspended tab and it still unsuspends by clicking anywhere.

As for installing an older version, i came across this website which has archived all the older versions: https://crx.dam.io/ext/klbibkeccnjlkjkiokjodocebajanakg.html
NOTE: You have to click on the 'view source' link for the version you want, and then click 'download' or 'crx' in the top right.

Not sure how you'd go about installing the downloaded file on opera though. Perhaps do a google search for 'how to install crx on opera' or 'how to install opera extension from zip'.

Let me know how you get on if you do end up installing an older version.
