### ISSUE TITLE
"Never suspend active tab in each window" is being ignored when disabled

### ISSUE THREAD

**Issue by CollinChaffin** [deanoemcke/thegreatsuspender#762]
Uncheck the "Never suspend active tab in each window" checkbox and expect even (non-form-input) active tabs in each window that are not whitelisted to be suspended with others, yet after hours with a dozen windows open each and every active tab, and only that tab, is not suspended.  This is being observed in last couple commits (last few weeks 9/2018) and Win7x64.

**Comment by deanoemcke** [comment]
@CollinChaffin I'm unable to replicate this. Can you please confirm on the latest master code (v7.0.124).
Thanks.

**Comment by CollinChaffin** [comment]
Hi @deanoemcke  I swore I opened an issue on this already a LONG time ago amidst numerous other issues, and it turns out I did and I apologize for not getting back to it.  As I double-checked I came across at least one other that is clearly due to this - issue #791 if you look his 4th tab not suspending is his active tab.  This is because the option `Never suspend active tab in each window` simply does not and HAS NEVER worked - period.  No matter what build of Chrome or TGS I have yet to I think ever see my active tab suspend, even with that box unchecked.  I have rechecked it to then uncheck it thinking it was stuck etc.

Testing has been performed on various builds of Chrome/Chromium with various builds of TGS, up to the very latest commit `7ad3174016e6a7527993ac224a599ef389458a97`.  Testing consisted of reducing auto-suspend timeout to `20 seconds` to speed testing (other timeout values were also tested).  All other Chrome/Chromium extensions were disabled.  Various tabs were opened, ensuring none had active forms/form input.  Tabs were activated at random intervals and finally a period of 30 seconds was allowed to pass on the last active tab.

The results were the same in all testing.  Despite experiencing the various previous bugs related only to the TGS icon display, in 100% of the cases TGS properly suspended every tab EXCEPT one - the active tab.  There was no test that resulted in auto-suspension of the active tab being displayed.

Logging results show the active test tab is always flagged as status "normal" and not as a inputform as shown here, and as you can see the final active tab can be left for eternity (with the 20sec timeout I let it sit for hours and this is what is in the TGS debug log):

![snag_1-17-2019_17-38-52](https://user-images.githubusercontent.com/9301483/51356211-59b95e00-1a7f-11e9-9d87-3dd790ed8547.png)


Is this a case of code is negated via an incorrect double-negative?

```
//active: a tab that is active (and IGNORE_ACTIVE_TABS is true)
```
Okay let's trace where that value is set.

The IGNORE_ACTIVE_TABS is a boolean.  The question on that boolean checkmark says "NEVER suspend - BIG NO TO SUSPEND ACTIVE, check this if that's what you want" - so I UNCHECK it because I DO want active suspended - making the boolean value FALSE.  So, let's apply that to our action of "Is it true that you DO NOT want to suspend active tabs?" which is now assigned that FALSE.  Perfect and correct.  Now comes my question which is why I believe somewhere the code logic around it is coded in a way that this also seems a bit backwards how it is being set.  Since we now have our `dontSuspendActiveTabs` set to FALSE (meaning simply DO suspend them), this code then sets:

```
var dontSuspendActiveTabs = gsStorage.getOption(
      gsStorage.IGNORE_ACTIVE_TABS
    );
```



I don't know how much more complex a simple "SUSPEND_ACTIVE" boolean of TRUE/FALSE can be, LOL..  Because when you check the box on the options form, according to that code it sets the value of `dontSuspendActiveTabs` and is NOT negated but correct  and simple - I now UNCHECK it to set to FALSE.

But what happens when it's read back in via gsStorage stored value:
```
IGNORE_ACTIVE_TABS: 'gsDontSuspendActiveTabs',
```
So for me, here is what I believe is the root cause - IGNORE_ACTIVE_TABS is now set to FALSE based on the above line when it's read back in - meaning instead (because of the double negative) DO suspend the active tabs - the exact opposite of what it is supposed to mean.

Outcome:

1. My head hurts
2. Active tabs don't suspend

My guess as I continue to debug is that the code is such that it then is acting more logical than the above, and negating it once more which is why the code as shown above via gsUtils logging is that when it comes to that value and active tab, NO code ever fires.  I say this because if it were only a single reversed value I should be able to instead set that value to checked/true and see activity in the log - and I do not.  It simply NEVER does ANYTHING to the active tab in my testing.

Now that I taught myself your gsUtils logging and I've shown it above, could you now either provide me a way to provide you additional info (I think I'm taking considerable time already providing good detail) and if there is any recent demo showing the active tab suspending and the options etc. it would be helpful because this has been broken a very long time and others are complaining about it too and I am trying to assist but you know your logic on these things better than anyone.  I can certainly submit another PR but really look at the above and try to understand how as a DEV myself, those double negative values simply don't seem to compute so I have no idea how it could be working.

**Comment by deanoemcke** [comment]
@CollinChaffin Thanks for the detailed analysis. And sorry for the bad use of the negative wordings for the booleans. I agree it confuses things.
However, I'm still unable to replicate this issue :(

Firstly, you reference issue #791. I don't believe this is an active tab issue, you're correct that his active tab is the 4th (rightmost) tab, but the user is commenting on how the LEFTMOST tab (not active) is not suspending. Hence him saying that only 2 instead of 3 (out of the 4 tabs) are suspending.

Secondly, while the wording in the code is confusing, i don't believe there is an error in logic there. `IGNORE_ACTIVE_TABS` and `dontSuspendActiveTabs` mean exactly the same thing. Ignore meaning, when looking for tabs to suspend, ignore (ie dont suspend) these (active) ones. When this is set to FALSE, active tabs ARE suspended, which is in keeping with having the 'Never suspend active tab in each window' option UNCHECKED.

There is a very definitive way to see if an active tab (in a non-active) window is going to suspend automatically. The TGS debug page will show the 'status' of each tab. If the tab has a status of 'active' then it will be ignored (ie. it will NOT suspend). If it has a status of 'normal' then it WILL automatically suspend.

Try this experiment: Start a chrome session with just a single window and open two tabs, one for TGS settings, and one for TGS debug page. Then open a second window, navigate to any url and return to the first chrome window. If you refresh your debug page, you should see the tab in the other window appear in the debug tabs list. If you have the 'Never suspend active tab in each window' CHECKED, then this other tab should show a status of 'active' and have no time to suspend specified. If you then UNCHECK the 'Never suspend active tab in each window' option and refresh the debug page, you should now see that that tab in the other window has a status of 'normal' and it will have a time to suspend specified (depending on what you have set for your 'Automatically suspend tabs after' option.

Can you try that and report back your findings? It seems to me that if you are experiencing the issue of active tabs (in non-active windows) never suspending, then the status of these active tabs will always read 'active' regardless of whether you check or uncheck the 'Never suspend active tab in each window' option.

**Comment by CollinChaffin** [comment]
OMG I've been updating the wrong issue.  Please see my last few comments/info I just posted today over on my other open issue #843.

**Comment by deanoemcke** [comment]
@CollinChaffin I think I may know what is going on here. 

It's possibly just a misunderstanding of what this feature is supposed to do. It is meant for users with multiple chrome WINDOWS open. Actually, ideally for users that have over 20+ windows which would mean it is able to suspend another 19+ extra tabs.

Unchecking 'Never suspend active tab in each window' will allow the active tabs to suspend, but only for the NON-CURRENT windows. The active tab in the current window (the dev-tools window does not count as being the current window even if focused) will NEVER suspend, regardless of what you have set in your settings. This is because it is assumed that this is the tab the user is currently looking at.

Note that this has nothing to do with whether chrome itself is currently focused in your window manager. Even if chrome is minimised, the currently active tab in the currently active window will never suspend automatically.

When you click the extension popup menu for this tab, it says 'This tab will suspend automatically' but this actually means 'This tab will suspend automatically WHEN the tab is no longer the active tab in the window, or when the tabs window is no longer the currently focused window'.

In the debug log, when it says 'This tab is not eligible for suspension' it is because it is the currently focused tab in the currently focused window.

This is just the design decision I have decided upon with this feature. It COULD suspend this tab, but the cost to the system is just a single unsuspended tab at most, which is pretty minimal. The reason I implemented the 'active tab' feature at all is because I realised there were users that had 100+ different chrome WINDOWS open, and add this feature could allow them to suspend a significant number of extra tabs automatically.

Please let me know if I've identified your issue correctly. And let me know any thoughts you have on this.

And thanks for the video. It always helps a lot when dealing with these confusing scenarios.

**Comment by CollinChaffin** [comment]
Doh!  Double-doh!  Can I ask if you've considered though the cases where if you know you have this extension, and knowingly set away from the default (which is to never suspend active), that after reading a tab and walk away from the computer, that with a 1-hour suspend for example instead of Chrome sitting active with it's background processes potentially running on the active (now let's refer to it as VIEWING tab) -- that it should be an option, whether being included as part of what today is constituted as "active", or whether it is added as another checkbox for "current viewing tab"?

I'm certain you're aware since you created this extension, but many people are not as to just how active Chrome really is when left on an active tab.  Just open taskmgr load the I/O columns and a single tab to www.google.com and be amazed at how much Chrome winds up reading/writing to cache and using CPU for it's internals.  This is even more so with the new "simple" caching.  As someone who has personally now literally has not one, not two, but THREE new SSD's of differing brands DIE largely due to (and before using TGS with more aggressive timeouts) Chrome and having recorded this video demonstrating Chrome sitting IDLE with ONE tab open yet when added up, consistently performing 25-100 GIGABYTES of SSD nand WRITES PER DAY:

https://youtu.be/Rydy1bb0ApM

The upshot it you're absolutely correct in that I understood the "active tab" setting to include the actively viewed tab.  With that said, I would ask you take a look at this video if you're not already aware of just how hard Chrome is on a SSD in that case of having just that one, single, viewing tab never suspend.  If it is an hour after I'm done reading it and have had to walk away from my system I would sure love it for TGS to still suspend assuming no active form input.   In my testing with this I noted that TGS does already detect and register clicks inside the "viewing" active window, so simply using that as the timeout "activity reset" the same as screensavers do it, then even with a 15 min setting when I'm reading a tab I certainly have to click on something at least every 15 min, anyway, so doubt I'd get many unwanted suspensions even set to 15min.  I think you'd find it would be a very welcomed (and if you took a poll I would bet commonly enabled) feature/option and having looked more at the code guessing it would literally only take a few lines of code being changed to implement.

**Comment by deanoemcke** [comment]
@CollinChaffin You have a legitimate point. I think the best way forward from here is to make a new gitHub issue as a feature request for the above, stating your case as to why you think it would be useful.
Thanks for all the feedback Collin.

**Comment by CollinChaffin** [comment]
Sorry missed your last response looks like this last commit addresses this?  https://github.com/deanoemcke/thegreatsuspender/issues/877
