### ISSUE TITLE
TGS forcibly restoring prior session upon every Chrome restart

### ISSUE THREAD

**Issue by CollinChaffin** [deanoemcke/thegreatsuspender#781]
Latest commit bf02517 `(Oct 8th)` on top of the tab order issue I opened also appears to have a very serious bug where EVERY single time I open Chrome now, ALL prior suspended tabs are being restored - with a brand new tab I've never seen before from TGS stating as much that it is restoring almost like a crash occurred (when it was closed gracefully).  This never occurred in the past nor do I see any new options to disable this behavior.  I have confirmed this on multiple Win7x64 systems all running latest Chrome DEV `(Version 71.0.3569.0 (Official Build) dev (64-bit)`.

I have always opened Chrome fresh and TGS never restored anything automatically and since I also save my sessions using another extension (sessionbuddy) I typically will manually re-open and restore my saved sessions with SB and not TGS - **but usually I reopen and begin a fresh zero session restoring saved (still TGS suspended!) tabs only as needed using SessionBuddy**. 

Is this change just an inadvertent bug?

**Comment by deanoemcke** [comment]
This was a bug recently which I had thought I'd fixed. Could you please let me know two things.
1. What version of the extension are you using when you see this behaviour?
2. What do you have set under chrome settings -> on start up?

Can you also please try the latest release and let me know if this is still happening (v7.0.129)?
Even if it seems to be fixed in the latest release, it would still be great to know the answers to the two questions above. 

FYI: It's closely related to this bug: https://github.com/deanoemcke/thegreatsuspender/issues/768

Thanks.

**Comment by CollinChaffin** [comment]
Sorry missed your question until now and we are far past that version it is still the same in today's commit 63a04dc, WIN7x64, Chrome x64 DEV 71.0.3573.0 although this has persisted now through multiple versions of Chrome x64 and TGS.  This is dangerous because it's now to the point that it's actually changing the underlying behavior of the web browser and forcibly re-opening 100% of the last session upon every restart, without any ability to even disable the behavior.  The good news is it does not sound like from your comment above that it is by design intentional (although TGS has always offered OPTIONAL session management that was totally passive).  I have never had any issue with TGS storing my session data however - and you may want to just throw this into the back of your head - IF I had been at any time offered a single "disable" switch on the session management tab, I would have and with it probably reduced the overhead of TGS substantially as well as ensured this COULD not happen to those of us not using that feature to begin with.  Regardless, you obviously don't want TGS users to need to lend serious thought into the full state of your entire browsing session and all windows/tabs before clicking the "exit" each time knowing that ALL of it will start back up at the same time when you next click the Chrome icon for a quick single-page lookup. :)

I can certainly also create a video of this if you need it but I'm guessing you understand what's happening here.  I can tell you that it also just happened when I did a very minor 1-2 commit update without any kind of database compaction etc. and I NEVER EVER let ccleaner delete anything but cache and non-approved cookies (when I run it).  I do not clear session data, history, download history, OR ANY EXTENSION DATA. it is literally those 3 things, general cache, cookies, and do a database compaction which does I'm sure flush any uncommitted journals.  I thought it might be related but it seems to be happening even when I do not run it.  Either way, I have trouble understanding which of those (if any) would suddenly (and not for the last YEARS I've used it) be causing TGS to now believe a crash occurred and restoring like this.  And, since others are getting any kind of TGS tab popups on every Chrome start, just spit-balling but sounds like some code is causing it all. :)

For the record, when I do run it, these are the few options I even activate:

![snag_10-17-2018_14-31-03](https://user-images.githubusercontent.com/9301483/47111521-5bbe1780-d219-11e8-9635-5472adecc3f2.png)

**Comment by deanoemcke** [comment]
@CollinChaffin actually, a video would be great, as it's hard to picture the exact flow of what is happening to you.
If you could make a video that shows the session BEFORE closing chrome, and then the entire chrome restart process ensuring that the bug you've described is also visible.

And secondly, if you could let me know what you have set under chrome settings -> on start up, that would be super helpful.

Thanks!

**Comment by CollinChaffin** [comment]
This continues to happen I can shoot a video but here is what the video is I cannot understand how on earth this is "difficult to picture":

1. Close Chrome with TGS enabled - no crash.  Chrome set to open to blank NTP (which is does until TGS restores tabs).
2. Open Chrome:  Bug/New behavior/root of this issue=TGS even displays it's branded "please wait while your session is restored"....and all my tabs from the prior close re-open.  

I'm confused, do you really need a video of that?  How Chrome looks closing and opening and how the TGS "I'm restoring your session" looks?  That's TGS in action doing a session restore - just one I didn't order.  I will if you need it but as a DEV myself no idea how that could possibly help you.  Can I ask about all these (probably a dozen+) commits specifically for "improve logging" are?  I have not read the code but I've been watching them appear for months is there truly still not a way to enable ANY logging in TGS that can instead prove through basic logging what I keep having to spend time shooting/editing videos of that others also confirm is happening with a simple enable of debug logging?  I ask because to date in all these issues despite all these "logging" commits, you've still never instructed me once on how to collect ANY logs, or even indicated TGS is producing any.  I myself would also find it incredibly helpful in troubleshooting to have a TGS log to see just what TGS is doing as it initializes, and what it's parsing when it believes I crashed when I didn't and begins it's session restoring.

Sorry for the frustration but is seems like you've questioned almost every issue I've even stated was also happening to me, or ones I was first to open that I finally then have to waste the time to shoot videos to prove it, and clearly you must see there has been something to so far EVERY single one I've opened since there has been probably twenty or so commits specific to trying to fix what I think now you realize is/was a serious issue in the new code refactoring with and without the built-in Chrome discards, since as of last night all had finally been fixed to at least show favicons EXCEPT in the most important one - the automatic "wait 15 min" suspend which is STILL broken.  I also shot a video of that over in issue 478 (several, actually) to back up what others had already reported.  

This issue #781 is simple - clearly you're doing something to change/enhance (it wasn't broken or lacking that I could tell before) the quiet session management/recovery be it for enhancements or just due to your refactoring.  Two months ago, I had literally NEVER ONCE seen the TGS session restore, nor manually utilized that entire feature.  Now, EVERY TIME I open Chrome, I have a totally unwanted feature of TGS forcing itself on me restoring tabs.  I don't want that.  I had no issue with the feature being there, but it never forced itself before so if this is now the norm to forcibly open tabs at Chrome startup, whether I execute ccleaner at all or not (it just happened when all I did what close Chrome, wait 10 seconds, and re-open it) then please wouldn't it be easier for YOU to add a simple enable/disable killswitch (checkbox) at the top of the session management page so those like me that don't even use TGS session management can disable it?  Then if we need to report an issue to you, our report automatically eliminates half the code-base dealing with sessions not to mention all that code overhead that never would need to execute.

As a DEV been doing this over 30 yrs I also often have taskmgr open anyway, watch ALL chrome tasks die off when I gracefully close chrome (if I run ccleaner it won't even execute if Chrome is active) but regardless of if I do nothing but re-start Chrome, or clean basic cache, TGS is doing something it never did - just like all the other recent new behaviors we've been struggling with.  Hopefully you can instruct me on how to enable some better TGS logging.

None of my settings have changed - TGS has. Here is my startup:
![snag_10-28-2018_02-06-55](https://user-images.githubusercontent.com/9301483/47613100-3682a200-da80-11e8-81a2-ce5b491dee7a.png)

I do not (nor EVER have) allowed Chrome to continue running.  When I click "close" - 100% all CHROME.EXE tasks gracefully terminate per taskmgr:
![snag_10-28-2018_02-07-09](https://user-images.githubusercontent.com/9301483/47613110-78abe380-da80-11e8-82ae-fcd612562ea5.png)

**Comment by CollinChaffin** [comment]
Hey @deanoemcke Dean!

I wanted to follow-up to let you know between the last round of refactoring and commits, and the Chromium issue below that I opened (and they resolved by reversing a bad commit) that also I believe may have been contributing to at least some of the extension crash behavior of TGS (it was with a few others very badly) and that things are looking better regarding this issue and I'll close it out to let you work on some of the other ones that have been rearing their ugly heads up yet again (namely your favorite, the favicon refreshes, LOL!).

Thanks for working this one in with the others!

[Multiple extensions suddenly crashing repeatedly/frequently](https://bugs.chromium.org/p/chromium/issues/detail?id=901010)

**Comment by CollinChaffin** [comment]
Update, I am no longer seeing the "crashed" message I recorded which I believe was caused by the Chromium regression that was fixed, however I am unfortunately still seeing TGS merely re-open sessions almost randomly without anything other than the TGS window/tab flashing that says that TGS is "please wait while your tabs are restored" and restoring the entire last session without asking.  What is odd is then the next reopen it will not so perhaps there is still a crash of some kind being detected (right or wrong) by TGS behind the scenes but without any debug logs I still have no idea how to help troubleshoot further.

Note this is with DEV build but since that is not as far from stable as Canary it is worth mentioning if we do nothing it could become reality very quickly - so if we need to get the Chromium team involved again just let me know how I can help!

**Comment by deanoemcke** [comment]
@CollinChaffin Hi Collin, and sorry for any extra digging i've asked you to do on some of the issues you've posted. Thanks heaps for getting back to me with more details. It's invaluable having people on the frontline testing out the latest development version of the code.

Here's some answers to your questions:
> This continues to happen I can shoot a video but here is what the video is I cannot understand how on earth this is "difficult to picture":
The video request is a last ditch effort to try and get to the bottom of what is happening here. I don't deny that there is an issue, and others have reported a similar thing. Only, I have been unable to replicate the latest issue, and so I thought that perhaps if I saw a video I'd see something there that I had overlooked - like some subtle difference in what you were doing compared to what I have tried when I attempt to replicate it.

> Can I ask about all these (probably a dozen+) commits specifically for "improve logging" are? I have not read the code but I've been watching them appear for months is there truly still not a way to enable ANY logging in TGS that can instead prove through basic logging what I keep having to spend time shooting/editing videos of that others also confirm is happening with a simple enable of debug logging? I ask because to date in all these issues despite all these "logging" commits, you've still never instructed me once on how to collect ANY logs, or even indicated TGS is producing any. I myself would also find it incredibly helpful in troubleshooting to have a TGS log to see just what TGS is doing as it initializes, and what it's parsing when it believes I crashed when I didn't and begins it's session restoring.

There is indeed console logging! I'm sorry I've never mentioned it to you, and in this instance a log might prove invaluable if you can replicate the issue. To enable debugging, open the extension settings page and in the url, change options.html to debug.html.
This will take you to a hidden debug page which allows you to turn logging on and off. Toggle logging on for both debugErrors and debugInfo.
After that, if you open the extension background page (in devtools) you should see a LOT of debug output. The stuff at the very start is the part of interest as it logs why it makes the decisions is does around session restore on startup.

> ...since as of last night all had finally been fixed to at least show favicons EXCEPT in the most important one - the automatic "wait 15 min" suspend which is STILL broken. I also shot a video of that over in issue 478 (several, actually) to back up what others had already reported.

I assume here you are referring to this post you made on issue 478 on the 24th October:
> ...HOWEVER--for some reason I just watched as a few tabs that performed an AUTOMATIC suspension wound up still suspending incorrectly to a blockhead icon. Of note, after seeing the promising results from manual suspensions, I have once again been running with the new option re-enabled to utilize Chrome's native discarding which may still be impacting the AUTO suspend. I will perform some more thorough testing of the AUTO portion later this AM and report back the results.

You mentioned that you would report back with results but seeing as you haven't i assumed the issue was resolved. It's odd that you specifically mention 15 minute auto-suspend. I would have thought that it was equally as likely to occur with any time period. I use the 20sec timer when testing this stuff and haven't had any issues with the favicons on automatic suspend so far. Once again though, if you can replicate this, a recording of the log during the issue would be super useful, especially if you can identify the tab id that is causing issues, as all log entries report their tab id to help follow the process flow for each tab.

> ...wouldn't it be easier for YOU to add a simple enable/disable killswitch (checkbox) at the top of the session management page so those like me that don't even use TGS session management can disable it? Then if we need to report an issue to you, our report automatically eliminates half the code-base dealing with sessions not to mention all that code overhead that never would need to execute.

I understand your frustration here. But if there's a bug, I'd rather identify it and fix it, rather than provide an option to turn off some valuable functionality. If said functionality was turned off manually by a user, then when the extension updates all of their suspended tabs would disappear and WOULD NOT come back. This is not really an option.

> As a DEV been doing this over 30 yrs I also often have taskmgr open anyway, watch ALL chrome tasks die off when I gracefully close chrome (if I run ccleaner it won't even execute if Chrome is active) but regardless of if I do nothing but re-start Chrome, or clean basic cache, TGS is doing something it never did - just like all the other recent new behaviors we've been struggling with. 

All these new issues have arisen due to a complete overhaul of the session and favicon codebase. And this was mostly in response to some major changes in Chrome that caused the earlier version of the extension to fail in some pretty significant ways. So going back is not really an option.

> I do not (nor EVER have) allowed Chrome to continue running. When I click "close" - 100% all CHROME.EXE tasks gracefully terminate per taskmgr:
> ![image](https://user-images.githubusercontent.com/1051763/48458876-f287ef00-e82c-11e8-893c-c06328e6c835.png)

This is interesting. I do not have that option in chrome on my mac (in either the production build or canary). Perhaps it is a windows specific thing? Perhaps I'll need to check that out on my PC.

**Comment by deanoemcke** [comment]
@CollinChaffin I've managed to recreate this and should be fixed in the latest release v7.0.143  🎉

**Comment by CollinChaffin** [comment]
@deanoemcke I just tested and it looks good I think you finally nailed it!  Thanks!

**Comment by JasonBaby87** [comment]
Hi! I'm just trying understand here. This is fixed in v7.0.143, but the store is only up to v7.0.109.

The issue stated in this issue is pretty annoying. So I would like to ask when this will be fixed "officially".
