### ISSUE TITLE
Keyboard shortcut for "Force suspend all tabs in all windows" does not apply to active window

### ISSUE THREAD

**Issue by CollinChaffin** [deanoemcke/thegreatsuspender#782]
EDIT:  Adjusting the hotkey I originally stated force all tabs in all windows, is actually the non-force suspend all tabs in all windows.

Latest commit `bf02517` (Oct 8th) has another issue where the same command is not rendering the same action whether selected via context menu vs. keyboard shortcut/hotkey.

To reproduce this issue:

Keyboard shortcuts, and set:

`Suspend all tabs in all windows  --  Alt+Shift+S`

1. Open 2 or more tabs to any active pages
2. Right-click the active tab's page, from TGS context menu select the "`Suspend all tabs in all windows`"

Result:  All pages, including the active page that was clicked upon, are correctly forcibly suspended.  No active unsuspended tabs remain.

BUG:

1. Set the hotkey (I used Alt+Shift+S) for the same option to "`Suspend all tabs in all windows`"
2. Open 2 or more tabs to any active pages
3. With one of the active pages active, press the hotkey set above (I used Alt+Shift+S)
4. All tabs **except the currently active tab** are forcibly suspended.  One tab is erroneously left untouched by the suspend command.

EDIT:  The "Force all tabs in all windows" actually DOES work via hotkey to match the menu command as expected, whereas this one does not.

**Comment by deanoemcke** [comment]
This is a little confusing. Based on your edits, you're saying the issue is with the 'Suspend all tabs in all windows' hotkey, and NOT the 'Force suspend all tabs in all windows'?

Just to clarify what this option is supposed to do, it basically 'fast-forwards' the auto suspension timer on all tabs and will only suspend them if they would have suspended normally (as opposed to force which suspend no matter what).

As far as the active tab goes (in the currently focused window), this will never be suspended using 'Suspend all tabs in all windows'. The active tabs in non-focused windows WILL suspend unless you have the 'Never suspend active tab in each window' option checked.

I have tested the above behaviour in the current release and it works as expected, both via the context-menu, and the hotkey.
