### ISSUE TITLE
Welcome Page Tab opens EVERY TIME, please make it stop 

### ISSUE THREAD

**Issue by ntinla** [deanoemcke/thegreatsuspender#785]
I love TGS thanks for creating it. But am having an issue that is utterly annoying and enough to remove TGS from Chrome. 

The Great Suspender welcome page opens a new tab EVERY SINGLE TIME I open Chrome. I have security Chrome extensions so that Chrome clears data every time I close Chrome, I'm not willing to change this, if that's the reason. When I open Chrome, I immediately begin typing in something, and the tab that TGS opens interrupts that process every single time. I am a grad student and disrupting my thinking process is quite frustrating. 

Please let me know how to stop this from happening. Otherwise thankful for the app and happy to donate if this can be resolved. 

Thank you,
A user 

![screen shot 2018-10-09 at 7 26 05 pm](https://user-images.githubusercontent.com/44011880/46709895-9eb93300-cbfa-11e8-810c-6b365263060b.png)

**Comment by deanoemcke** [comment]
You are correct in your assumption that this is happening because you are clearing your local storage for the extension every time you close Chrome.

I've given it some thought, and realised there's room for improvement here. I will now try to differentiate between users who are installing the extension for the first time, and users who have already installed the extension on a different computer with the same chrome profile.

When you install an extension on one chrome profile, it automatically installs it on other computers logged into the same profile. It would be nice for these other automatic installs to not receive the welcome message.

All this is to say, if you simply clear your local history (as I suspect is all you are doing) the extension will treat this as if you are undergoing an automatic install, and it will no longer show the welcome screen.

This has been implemented in development version 7.0.131 and will be pushed to the webstore soon. 
I hope this is useful to you.

**Comment by SnIPeRSnIPeR** [comment]
Haha, I have the same situation. I have one question. when you will add new version with this fix to the Chrome Web Store?

**Comment by pandaassassin987** [comment]
This is a problem I would like fixed as well. I have this extension linked with my school account, so every time I log into a school chromebook, the welcome page pops up. Once you implement the feature you mentioned earlier, I can let you know if your solution works for me. Thanks!

**Comment by CollinChaffin** [comment]
I don't know if this is related but this forcible auto-restoration of my last session anytime I simply clean the cache using ccleaner sure seems to be related.  TGS NEVER did this until recently I fully understand it has it's own session mgmt but PLEASE PLEASE at this point since it is obvious there are and will be continued efforts to make the session management more robust add the one CRITICAL missing setting that has always been missing (but never really mattered until now) - A WAY TO OPT OUT AND DISABLE IT.  I love TGS, but frankly already use SessionBuddy for a far more mature session management so in the near term will never use TGS for session management but it is tied with SB as my number one extension for what it does best - suspend tabs and save me from myself when it comes to browsing practices. :)

Just a single checkbox to disable all session management and continue to allow TGS for suspensions - pretty please!

**Comment by deanoemcke** [comment]
@CollinChaffin I'm not sure if you're posting this in the correct issue. You seem to be referring to previous sessions restoring when you restart chrome, whereas this issue is about seeing the welcome page when you restart chrome. Did you mean to post in this issue instead? #781

If so, can you please get back to me in that other issue with my questions I asked of you? It's an issue I would like to have resolved if possible.

As far as an option to disable session management, what you're encountering is not so much session management, as it is tab recovery. As you probably know, when the extension updates (or crashes), all suspended tabs disappear. To help mitigate this issue, I try to automatically restore these tabs after the update/crash.
In your case, the extension is falsely detecting that you're recovering from an extension crash and is trying to recover your tabs. That is why it would be useful for me to get more detailed information on exactly what chrome settings you have, and what tabs you have open when you encounter this issue.

But please, respond to this in the other issue.
