### ISSUE TITLE
'Suspend all other tabs' suspends only two of three (in 4-tab window)

### ISSUE THREAD

**Issue by mkz7** [deanoemcke/thegreatsuspender#791]
– Wanted to figure out how to suspend **all** tabs in the current window (not just 'all other' tabs). 
– Was in Google Docs, where browser right-click context menu isn't available (appears to be reserved for GDocs pop-up menu). Right-click context menu doesn't have option to 'suspend all tabs in current window' anyway.
– So instead selected toolbar option (via TGS icon) to 'suspend all _other_ tabs'.

As is shown in the screenshot, the tab on the far left did not suspend. (I was in #4 when I selected 'suspend all other tabs'.). 

![image](https://user-images.githubusercontent.com/16544283/46923670-419df280-cfe9-11e8-8afa-3180765c3e43.png)

Am I missing a way to suspend 'all tabs in the current window'?

Thanks.

 * Extension version:  v. 7.0.109
 * Browser & version:  Brave Dev. 
 * Operating system & version:  Mac 'High Sierra' (v. 13.9.5)

**Comment by deanoemcke** [comment]
What happens when you click on the tab that failed to suspend? The popup menu icon will change depending on the currently focused tab. And when you click on it (the popup menu icon) it will tell you the status of the current tab.
If the icon is grey, it means that the tab won't automatically suspend (or respond to a 'suspend all other tabs' request). If it is normal colour, then it _should_ respond to this request.
In the latest release (not yet on the chrome webstore) the right-click context menu (and the keyboard shortcuts) now has an option to 'force suspend all other tabs in this window'. Which will force all other tabs to suspend regardless of their status.

There is a chance you're seeing a bug. Or perhaps that tab is receiving form input which is why it won't suspend.

**Comment by mkz7** [comment]
At the time that I experimented with 'suspend all other tabs' (i.e., with four different GDocs documents in four different tabs in the same window), all four tabs were open but static.

There wouldn't have been any form input active at the time, since all four tabs just contained a single line of text, with variations in the text intended only to distinguish them from one another.

I located in Tab #4, then selected the 'suspend all other tabs' option.

I saw the icons for Tabs 2 and 3 fade, while that for Tab 1 did not change.

I don't have those tabs open currently, but in reply to your question, since Tab #1 apparently didn't suspend I assume that if I clicked on it it would react like a normal tab (i.e., establishing focus in that tab). 

Do new TGS releases auto-update or is it necessary to reinstall the extension via the Chrome Web Store (or other source)?

Thanks.

**Comment by deanoemcke** [comment]
@mkz7 ok, well i think all i can do is wait for it to happen again for you, and when it does, if you could check the tab status and report back.

one other thing to check is your setting to screen capture. if this is turned on, then it can sometimes take a while for a tab to suspend while it's generating the image preview.

for the updates, your extension will automatically update, but it may be a week or so before that happens. if you want a newer version earlier, you can install from source from gitHub.

**Comment by mkz7** [comment]
Thanks. No 'screen capture' -- I don't use it because of your warning about the addt'l memory it uses.

I'll let you know if the issue recurs. That was the first time I ever used the option to 'suspend all other tabs'.
