### ISSUE TITLE
Strip extension prefix when bookmarking suspended tabs

### ISSUE THREAD

**Issue by gooddadmike** [deanoemcke/thegreatsuspender#81]
I have been bookmarking all open tabs lately and when I open the tabs that were Suspended it tries to render them as suspended tabs in this extension then reload them. 

Sometimes it doesn't work and just loads a blank page. Is there any way you can set the extension to remove the extension prefix when bookmarks are being saved?

**Comment by deanoemcke** [comment]
Unfortunately I have not been able to work out a way to modify the url of suspended tabs so that it does not contain the extension id.
This problem has been raised before in issue #46. 
The chrome developers are looking into a possible way of enabling this in the future, but for now it is a limitation of the extension.
