### ISSUE TITLE
Please, help me recover my lost Saved Sessions (from IndexDB files)!

### ISSUE THREAD

**Issue by macsunmood** [deanoemcke/thegreatsuspender#817]
Hello and thank you for this great extension!
Unfortunatelly, I got a very sad issue: after PC startup crash (failed to come out of hibernation), lost my Saved Sessions and the extension seem to have deleted some database files from the IndexedDB.leveldb folder.
I've recovered (with a special software) some of the *.ldb files, which are dated just minutes before Windows went to hibernation (still not sure if they're enough). But when I try to put them in the "leveldb" folder, the extension simply deletes them.
Please, can you help me somehow read the information from these files, so I could recover my Saved Sessions (there were several) ?

### Specifications:
 * Extension version: The Great Suspender v6.30
 * Browser & version: Google Chrome 70.0.3538.102
 * Operating system & version: Windows 10 x64 (with latest updates)

**Comment by deanoemcke** [comment]
All I can suggest is that perhaps you're putting the files in the wrong location? Sorry but I don't know much more about manually manipulating indexedDb files than you.
I can only assume that if chrome is deleting the files, then they must be somehow corrupt.
You should be able to do some testing to make sure your process is working. 
1. Go to the url `chrome://version` to get your profile path (on my mac it is `/Users/dean/Library/Application Support/Google/Chrome/Default`
2. Find the extension indexedDb folders on your filesystem which should be within your profile path. ie: `/Users/dean/Library/Application Support/Google/Chrome/Default/IndexedDB/chrome-extension_klbibkeccnjlkjkiokjodocebajanakg_0.indexeddb.blob` and `/Users/dean/Library/Application Support/Google/Chrome/Default/IndexedDB/chrome-extension_klbibkeccnjlkjkiokjodocebajanakg_0.indexeddb.leveldb`
3. Create some saved sessions within the extension.
4. Backup the folders listed above.
5. Delete your saved sessions from within the extension.
6. Try to restore them by copy back over the backed up folders.

That will at least test the process on some known good data. Once you can confirm that works (I've not actually tried to do this before so it may not), then you will have a better idea how to restore from your possibly corrupt files.

Hope that gives you something to work with.
Let me know if you discover anything worth sharing with the community.

**Comment by macsunmood** [comment]
Thank you for answer!

> All I can suggest is that perhaps you're putting the files in the wrong location? Sorry but I don't know much more about manually manipulating indexedDb files than you.
I'm putting them right in folders you've mentioned.

> I can only assume that if chrome is deleting the files, then they must be somehow corrupt.
That's possible, but I assume the most (> 90%) part of files must not be corrupt. Is it still possible to read the session data somehow?

> You should be able to do some testing to make sure your process is working.
> 3. Create some saved sessions within the extension.
I've tried what you suggested, but it won't save anything at all! I tried it on another portable version of Chrome with the latest ver. of TBS installed - it works (and the deleted saved session recovery works as well - I confirm it), but when I put the files from the 'original' Chrome's TBS extension - the same thing happens..

I also wonder, what's the purpose of the .log files in the `IndexedDB/chrome-extension_klbibkeccnjlkjkiokjodocebajanakg_0.indexeddb.leveldb` folder? Do they contain any kind of sessions data? Looks like it, as long as when you start TBS from scratch (after deleting all IndexedDb folder files), it creates ONLY 000003.log file, and none of .ldb. What's it all about then?..

**Comment by deanoemcke** [comment]
@macsunmood 
i have tried doing what i suggested and it seems to work fine for me. that is:
1. backup the `chrome-extension_<ext_id>_0.indexeddb.blob` and `chrome-extension_<ext_id>_0.indexeddb.leveldb` folders in my `<profile_path>/IndexedDB/` folder
2. uninstall the extension from within chrome
3. reinstall the extension from within chrome
4. close chrome
5. delete the new folder created in the  `<profile_path>/IndexedDB/` folder
6. copy the old backup folders into the `<profile_path>/IndexedDB/` folder
7. restart chrome

doing this results in all my old settings and saved sessions.

As for your last question about `.log` files. I do not know exactly what these are or how IndexedDB databases are stored locally on the filesystem.

I'm not sure why the process I've described above does not work for you. It should as it does for me.
I would suggest trying to get that working again.

Also, perhaps your old backup could be from an older version of chrome? They may be some incompatibility trying to restore older indexedDb backups on a newer version of chrome? Just a guess though. 

If you wanted to send me your backed up folders (zipped) i could always try restoring them for you. I understand if you'd rather not though due to privacy considerations.

**Comment by macsunmood** [comment]
@deanoemcke 
I've done what you suggested with both installed (latest) and portable versions of Chrome - it keeps deleting the files on start. But he problem was that on the main installed version of Chrome the TBS extension doesn't save sessions anymore at all.

Anyways, here are the files: 
[recovered.zip](https://github.com/deanoemcke/thegreatsuspender/files/2628948/recovered.zip)
. Recovered with Magic Uneraser software.
Btw, there are 2 versions of a recovered `100239.ldb` file.
The date of files is just minutes before Windows went hibernating (before dramatically crashing next day).

**Comment by deanoemcke** [comment]
@macsunmood I've tried to recover based on your files but have had the same result as you :(

My only thought is that the backup you provided only contains `.ldb` files. My extension folder also has a `.log` file and several other files like `CURRENT`, `LOCK`, `LOG`, and `MANIFEST-xxxx`.

I suspect some of these files might be required in conjunction with the `.ldb` files you provided.

**Comment by ibash** [comment]
@macsunmood curious - what's so critical in the session that you need to recover it?
