### ISSUE TITLE
Feature request: Prevent duplicate tabs

### ISSUE THREAD

**Issue by Skipperio** [deanoemcke/thegreatsuspender#836]
If you open same website it would move you to suspended tab, old tab or new one.

**Comment by liamjohnston** [comment]
Can you provide more info?

Assuming you want this extension to block/warn or otherwise handle detecting you trying to open/suspend a url that is already open/suspended in a other tab... I would say that's not really in the remit of The Great Suspender. 

I'm guessing there are already other extensions that do this already? Not sure if they handle tabs managed by this extension (suspended tabs), but I reckon they would, assuming the suspended urls are the same.
