### ISSUE TITLE
Stopped working again!!! 

### ISSUE THREAD

**Issue by Bohojo777** [deanoemcke/thegreatsuspender#849]
Please complete the following information when submitting a feature request or bug report.
 * Extension version:
 * Browser name & version:
 * Operating system & version:

And please also do a search for your request/bug before create a new one thanks!

--------------

Not sure which version of The Great Suspender I'm using but know it's the latest. Browser is Chrome (latest) and Operating system is Windows 10. I would help to financially support this very valuable extension if it always worked or worked most of the time but it's constantly crashing or has a bug

**Comment by deanoemcke** [comment]
@Bohojo777 You will need to give me a bit more information as to exactly how it has stopped working for you. Otherwise I can't do much to help sorry.
And as @Jollfye mentioned, it would greatly help if you could give me your extension version. And ideally try the latest version of the extension if you're technically able.

Thanks.

**Comment by kliop00023** [comment]
check the commits for the fixed issues. i have encounter a lot yet no upgrade :(

**Comment by deanoemcke** [comment]
@kliop00023 the latest version within the gitHub project is ahead of that on the chrome webstore. i'm trying right now to update it.
