### ISSUE TITLE
Startup Chrome,  slow "unsuspension"

### ISSUE THREAD

**Issue by Jhoander** [deanoemcke/thegreatsuspender#859]
I'm a "tab hoarder" on rehab. That means trying not having more than 500 tabs open at once and keep Chrome under 30 Mb of RAM.
For that, I use this extension together with Tab Outliner to close windows that I don't need "right now".
The big problem is when starting Chrome where all tabs are unsuspended at once making the browser/computer freezing for about 5 minutes. Of course, all tabs need to be refreshed when you start but maybe a bit slower than all at once?

**Comment by deanoemcke** [comment]
@Jhoander Can you clarify for me whether the tabs are loading as suspended or unsuspended when you start chrome? That is, once everything has finished loading and your computer is responsive again, are the tabs in a suspended state or a loaded state?

I'm assuming you have 'Continue from where I left off' set in your chrome options.

From my experience, chrome has improved vastly recently in terms of startup time when restoring many tabs. It seems that these days it does not even attempt to load most tabs, it just sets the favicon and thats about it. This makes starting chrome with _unsuspended_ tabs actually really fast.

I've found the problem is actually trying to start chrome when restoring a lot of _suspended_ tabs. This is because unless I forcefully reload each one on startup, it won't set the proper favicon (it will use the default extension icon by default).

I'd like to explore this further if you have the time. Perhaps you could create a quick video to demonstrate what is happening for you? This seems to be a good program for achieving this: https://www.screentogif.com/

**Comment by belg4mit** [comment]
I've had this same issue for some time on ChromeOS, and more recently (and potentially related?) The Great Suspender process eats loads of CPU (50-110%) and RAM (900 Gb)... which kind of defeats the purpose of the extension. The behavior is now continuing beyond just start-up, even the previously suspended tabs are loading as suspended.

I am using the latest ChromeOS, and have 7 windows with about 300 tabs loaded (most suspended of course).

**Comment by belg4mit** [comment]
It looks like there might be pathological issue when the extension approaches 300 tabs? I killed the extension, and after trimming things from 303 tabs in 7 windows down to 253 tabs in 4 windows, after a bit of spinning around 70% CPU when restarting the extension it settled to 1-4% CPU and 300 Mb... which is the behavior I am used to. Previously it was eating monster resources and the RAM was leaking upwards.

**Comment by deanoemcke** [comment]
@belg4mit can you give me the version of the extension you are using? there was an issue with v7.0.109 (the current webstore version) that would cause massive CPU load once tabs reached a critical mass.

**Comment by belg4mit** [comment]
I appear to have 7.0.109 installed, presumably Chrome auto-updated at some point as I installed quite some time ago.

**Comment by belg4mit** [comment]
> I've found the problem is actually trying to start chrome when restoring a lot of _suspended_ tabs. This is because unless I forcefully reload each one on startup, it won't set the proper favicon (it will use the default extension icon by default).

Have you considered checking for icons in Chrome's existing cache? Is there a way to reuse a fetched favicon for multiple tabs? Many of my tabs are from the same site, but hitting the server a few dozen times to fetch the same resource would be unnecessary. It might also be a bit heavy-handed, I've noticed several other extensions store data in the bookmarks. Suspended tabs are more like bookmarks than what some of these extensions are storing, and the bookmarks in Firefox at least, store a cached copy of the favicon as well.  My apologies if you've already incorporated such optimizations.

**Comment by deanoemcke** [comment]
@belg4mit i have indeed incorporated most of those ideas already :)
favicons are retrieved from chromes cache, and the semi-transparent version of those favicons is cached within the extension.
the issue is actually with the suspended tabs. in order to update the favicon from the default, i need to be able to execute javascript on the tab. however, it seems that chrome has made some optimisations when restarting with lots of open tabs. it seems to lazy load non-focused tabs only when they gain focus. Which means that all the suspended tabs are unresponsive to commands from the extension. The only way around this that I have found is to request a reload of all the suspended tabs. Once they have reloaded, I can then run js on them to update the favicon and title.
