### ISSUE TITLE
Reopening closed tab (with Ctrl+Shift+T) will put tab at end of window

### ISSUE THREAD

**Issue by mihir6692** [deanoemcke/thegreatsuspender#867]
Please complete the following information when submitting a feature request or bug report.
 * Extension version: v7.0.109
 * Browser name & version: Google Chrome 72.0.3626.109
 * Operating system & version: Ubuntu 14.04

More Details :- 
When you reopen closed tab with Ctrl+Shift+T , it will put reopened tab at end of window.
Also if you open new tab from the reopened tab, it will open new tabs in old location of reopend window.

**Comment by deanoemcke** [comment]
@mihir6692 I'm unable to reproduce this issue. I also doubt that it is caused by this extension. i don't do any manipulation of tab ordering, so this extension should not have any affect on the default chrome behaviours.
you could try to disable the extension and see if you still have the issue. just be careful as it will cause all your suspended tabs to disappear. so either unsuspend all your tabs before disabling the extension, or back them up via some other method (like an external session management extension).

**Comment by mihir6692** [comment]
Yes, You are right, I tried with only thegreatsuspender extension , and it doesn't happen. When i added sidewise, problems surfaces. Will close this issue. 

Thanks for quick response.
