### ISSUE TITLE
Tabs Suspending Too Quickly

### ISSUE THREAD

**Issue by BevBam** [deanoemcke/thegreatsuspender#879]
Using The Great Suspender v7.0.109
Browser is Chrome 73.0.3683.48 (Official Build) beta (64-bit)
Using it on an Acer Chromebook 15

I searched and saw a similar issue but it was resolved years ago so I thought it was worth posting again.

My tabs are almost immediately suspending when they are no longer the active tab, and I have my settings set to suspend after an hour. So it seems like that time frame is being ignored. I have uninstalled and reinstalled the extension but it is still happening. 

Thank you!

**Comment by BevBam** [comment]
If I haven't included enough info or something, please let me know and I can offer more.

**Comment by Jollfye** [comment]
Download latest dev build from master branch as zip. Backup ur tabs + export them to file through TGS settings session management. Disable TGS v7.0.109 in Chrome Extensions but be warned that all suspended tabs will disappear once u disable extension so either have them backed up or unsuspended/loaded. Unpack previously downloaded zip somewhere to separate folder to save it there, great location would be to Program Files/Google folder with separate folder name smth like TGS or The Great Suspender. Load new unpacked extension from separate folder/src, that's where latest TGS dev build will be. To get back to v7.0.109 just disable latest dev build and enable v7.0.109, that's it. To update dev build download master branch zip with latest changes, exit Chrome, unpack zip and overwrite files in separate folder/TGS, open Chrome, TGS updated, done. Try to use TGS latest dev build and see if the issue u described persists. A lot was fixed by developer since v7.0.109. And I think ur issue may be fixed too.

**Comment by BevBam** [comment]
Hi Jollfye, I am using a Chromebook so I can't download and execute that I am aware of.

**Comment by Jollfye** [comment]
@BevBam well there's no need to execute anything, just download, unpack and install, google: chrome install unpacked extension, there should be videos how to, just download github master branch (that u could google too) and install from src folder, basically that's it, but still don't forget bout backup 😉

**Comment by BevBam** [comment]
Oh ok -- sorry to misunderstand. I will try that soon. Thanks!

**Comment by deanoemcke** [comment]
This is most probably due to the 'Instantly suspend when system memory gets very low' feature which is turned on by default in v7.0.109
More info can be found here: #596
