### ISSUE TITLE
Update the extension at the chrome webstore

### ISSUE THREAD

**Issue by Ferk** [deanoemcke/thegreatsuspender#89]
[The chrome webstore extension](https://chrome.google.com/webstore/detail/the-great-suspender/klbibkeccnjlkjkiokjodocebajanakg/details) seems to have version 4.74 (February 21, 2013), which is more than a year old.

There are some issues in the extension which might have been already solved, like sometimes the tabs going into suspension after very short time when they have been restored, even though the auto-suspend timer is set to 1 hour.

**Comment by OmgImAlexis** [comment]
@deanoemcke can this and #140 be closed now?

**Comment by deanoemcke** [comment]
A more recent version of the extension is now available in the chrome webstore. However, it has not been fully rolled out to all existing users (due to the potential of the update to cause users to lose some of their suspended tabs).
Not sure if I will ever fully push this out to all users. For now it will be available only for new users or people who uninstall and reinstall the extension. NOTE: if uninstalling then reinstalling, please unsuspend all tabs first. You will also lose any saved sessions so you might want to export them first.

**Comment by wizonesolutions** [comment]
Yeah, I had the dev version and lost some tabs. I got most back through Chrome history luckily, but yeah...definitely unsuspend all!
