### ISSUE TITLE
(FR) Ensure at least one tab per window is unsuspended before update.

### ISSUE THREAD

**Issue by yanamal** [deanoemcke/thegreatsuspender#895]
* Extension version: 7.1.0(after update)
 * Browser name & version: 72.0.3626.121
 * Operating system & version: Mac OS X 10.12.6

When all tabs in a window are suspended, an update to the chrome extension will trigger the entire window to reload (as if it was closed and reopened). This, in turn, makes the window do surprising things, especially in Chrome (window shape and position may or may not change, depending on what Chrome decides).

For this reason, the update behavior might be less surprising/confusing if at least one tab per window is *not* suspended at the time of an update to TGS.

(see also #891 )

**Comment by deanoemcke** [comment]
Just to provide context to this (as per issue #891):

Prior to extension update, the OP had multiple windows open across multiple mac OSX desktops/spaces. When the extension updated, because there was no unsuspended tabs in these windows, the entire windows were closed.
When the extension tried to recover these windows, it was unable to get information about which desktop/space the original window was in, and in addition, it cloned the dimensions of the currently open window for all the new windows.

A proposed solution for this could be to check for this situation prior to updating. For any windows detected that contain only suspended tabs, the extension could unsuspend onle the active tab in each of the windows before forcing the update. Thus, none of the windows would entirely close, and the update could restore the tabs into the existing windows, which would remain in their correct desktop/space and with the correct dimensions.

**Comment by deanoemcke** [comment]
This is now in master (v7.1.4)
