### ISSUE TITLE
Autodiscard sessions with 0 tabs

### ISSUE THREAD

**Issue by kalpaj12** [deanoemcke/thegreatsuspender#897]
I have a large list of sessions that get saved in `recent sessions` even though there are no tabs or windows in them.
Handling this redundancy would be essential, as I have to manually and painstakingly delete nearly 15-20 of such type.

**Comment by deanoemcke** [comment]
@kalpaj12 what version of the extension do you have?

**Comment by kalpaj12** [comment]
v7.0.109

**Comment by deanoemcke** [comment]
I'm pretty sure this has been fixed in the latest version (v7.1.0).
Although that just prevents zero tab sessions from being saved. It doesn't address the issue of why they are trying to be created in the first place.
For the latest version, just wait a few days. It's going to be pushed out automatically very soon.

**Comment by kalpaj12** [comment]
Hi @deanoemcke,
Sorry for the inconvenience. I thought all my chrome extensions were up-to-date. I can confirm that the issue has been fixed in the latest update. Thanks though. Closing issue for now.
Cheers!
