### ISSUE TITLE
The Great Suspender: Context Menu Links Are Gone

### ISSUE THREAD

**Issue by mettaseva** [deanoemcke/thegreatsuspender#907]
I absolutely love (and rely quite heavily on) The Great Suspender.

Unfortunately, a few days ago I discovered TGS has completely disappeared from my right click context menu. Please note that disabling and re-enabling the extension has not resolved the problem.

Any feedback/support you can provide will be genuinely appreciated.

- TGS: Version 7.1.0
- Chrome: Version 73.0.3683.86 (Official Build) (64-bit)
- OS: Windows 7 64-bit

**Comment by deanoemcke** [comment]
Try going into the extension options and unchecking, then rechecking the "Add The Great Suspender to right-click context menu" option.

Also, are you using incognito mode with the extension? Incognito mode does not provide a context menu.

**Comment by mettaseva** [comment]
Thank you for your prompt feedback.

I tried your suggestion of unchecking/rechecking the right click menu option both yesterday and just now. Did not make a difference in either case.

I am also not using incognito mode.

Any other suggestions or troubleshooting options?

**Comment by deanoemcke** [comment]
Where abouts on the page are you clicking? Try right-clicking on a part of the tab that only has whitespace.

**Comment by mettaseva** [comment]
I've been clicking everywhere on the page. From what I've observed (when the right click menu was working), I concluded that is important to click on the **background** of the page to activate the menu, so I always try to click in the white space, outside of any coded features in the page.

However, now that the right click menu has disappeared, I can no longer access it no matter where I click.

In light of this, I am wondering:

- Were there any recent updates to TGS that might have inadvertently caused this sudden change in behavior?
- Are there any known conflicts between TGS and other Chrome plugins?

**Comment by deanoemcke** [comment]
Hmmmm.. it's possible you're getting some errors that is preventing the context menu code from running. Would you be able to try debugging it on your computer? 

The wiki has instructions on how to enable the debugging log: https://github.com/deanoemcke/thegreatsuspender/wiki/How-to-enable-the-debugging-log

Once debugging mode has been enabled, go into the extension options and uncheck then recheck the "Add The Great Suspender to right-click context menu" option. Then check the console to see if it has generated any errors. The wiki also has information on how to save this log so that you can include it here.
