### ISSUE TITLE
TGS icon replacing web icon on tab after chrome restart

### ISSUE THREAD

**Issue by TonyRamirezz** [deanoemcke/thegreatsuspender#924]
When I restart chrome, every tab that is suspended has it's icon replaced with the too many tabs icon. I always have 3 chrome window open and anywhere from 20 to 40 tabs. 

Using Chrome on Windows 10

![tabs](https://user-images.githubusercontent.com/27990299/56283635-8b07ff80-613c-11e9-94c0-c31df36b5312.PNG)

**Comment by Jollfye** [comment]
fixed by developer some time ago, [update](https://github.com/deanoemcke/thegreatsuspender/issues/905#issuecomment-476802818) ur TGS extension

**Comment by TonyRamirezz** [comment]
But I thought chrome updated extensions automatically…

**Comment by JerryCMancuso** [comment]
I have been having the same issue, and it can be frustrating.

Extension Version:
7.0.109

**Comment by JerryCMancuso** [comment]
It looks like there _is_ a new version on the web store, but I wonder why it's not updating automatically through Chrome? There's no _Update_ option, just Remove.

![image](https://user-images.githubusercontent.com/3835584/56772250-01c97c00-677f-11e9-82d7-3801092ee557.png)

![image](https://user-images.githubusercontent.com/3835584/56772261-08f08a00-677f-11e9-80ba-8c25a90eab8d.png)

**Comment by liamjohnston** [comment]
@JerryCMancuso This has been mentioned a bunch of times in various issue threads (but I realise that isn't obvious):
The new version(s) are being rolled out to the webstore gradually to a % of random users, to make sure is isn't super broken first. If you weren't in that % of target users, you won't be auto-updated until the rollout % is increased to include you. 
Your options are to wait until then or simply uninstall and reinstall the extension. IMPORTANT: if you decide to uninstall, make sure you unsuspend any precious suspended tabs first, as they'll be removed when you uninstall otherwise. You might want to back up your whitelist settings etc too.

**Comment by Jollfye** [comment]
@liamjohnston hmm isn't there also an option in More tools -> Extensions to enable Developer mode and click Update button to manually check for extensions updates to get them even if they were still not rolled out to you but they are there, in webstore? So that there's no need to reinstall extension which u want to update. Plus I want to add that if we r going with uninstall-reinstall tactic to update I'm more for using some external option/extension to save/backup current session, windows and tabs (of course 
along with manually saving some TGS settings like whitelist etc) rather than just unsuspending tabs u want to save, there may be too many tabs to unsuspend and it could be a real pain to unsuspend them all at once or one by one, low ram pc would either take too much time to process or explode 😅

**Comment by TonyRamirezz** [comment]
> @liamjohnston hmm isn't there also an option in More tools -> Extensions to enable Developer mode and click Update button to manually check for extensions updates to get them even if they were still not rolled out to you but they are there, in webstore? So that there's no need to reinstall extension which u want to update. Plus I want to add that if we r going with uninstall-reinstall tactic to update I'm more for using some external option/extension to save/backup current session, windows and tabs (of course
> along with manually saving some TGS settings like whitelist etc) rather than just unsuspending tabs u want to save, there may be too many tabs to unsuspend and it could be a real pain to unsuspend them all at once or one by one, low ram pc would either take too much time to process or explode 😅

There is that option, but it seems like you can't update an individual extension this way - you have to update all at once which (if you have many extensions) could lead to a few surprises..

**Comment by TonyRamirezz** [comment]
The issue has been resolved. Thanks to the contributors I have discovered that extension updates are rolled out over  a period. However, it's possible to enable developer mode in extension management in Chrome and manually update extensions individually. Updating to the latest version solved the problem with too many tabs icon replacing site icon.
