### ISSUE TITLE
[Feature Request] "Never suspend active tab..."

### ISSUE THREAD

**Issue by DJPogoff** [deanoemcke/thegreatsuspender#930]
* Extension version: v7.1.0
* Browser name & version: Chrome Version 73.0.3683.103 (Official Build) (64-bit)
* Operating system & version: macOS version 10.14.4

In Settings, rather than "Never suspend active tab in _each_ window", one is more likely to want "Never suspend active tab in _active_ window".

Here is a nice way to implement this feature:

[Check Box] **Never select active tab:**
####[Radio Button] **in each window**
####[Radio Button] **in active window**

Upon checking the first line in my suggested implementation, the "each window" radio button defaults to selected, leaving the user to select the "active window" radio button, instead.

**Comment by CollinChaffin** [comment]
This also confused me for some time but the ACTIVE tab (the one you are viewing) will NEVER suspend the active tab being viewed.  In other words, open a non-form page, 20 windows with 10 tabs each - and set all options to allow suspending "active" tabs, and after the timeout you will only be left with 199 suspended tabs, NOT the 200 I personally would like to see (and have been requesting for years in the form of non understanding this was apparently by design).

Do you understand how that renders your request invalid, since all the "non active" windows ARE already what is covered by the active option.

**Comment by ossilator** [comment]
yeah, as-is, this task makes no sense. however, it can be easily salvaged by replacing "active" with "not minimized". see also my comment in #662.
