### ISSUE TITLE
No automatic update from v7.0.104 on?  Not sure how to proceed.

### ISSUE THREAD

**Issue by fuzzyweapon** [deanoemcke/thegreatsuspender#941]
Please complete the following information when submitting a feature request or bug report.
 * Extension version:  v7.0.104
 * Browser name & version: Chrome - Version 74.0.3729.157 (Official Build) (64-bit)
 * Operating system & version: macOS 10.14.5 (18F132) - mojave

Currently as I write this...

my client is on 7.0.104
web store is on 7.1.0

I didn't even know there were new versions until I was poking around for something else here.

So, I'm not sure what is the safe way for me to get the new update.  If there's any way to nudge it, or simply rip all my settings/current data and put it in the new one after uninstalling/installing from the web store. 😦

**Comment by sheershoff** [comment]
Well, I was looking how to resolve a problem with TGS obviously switching focus to a tab/window being suspended and stumbled upon this issue. I've just successfully upgraded TGS with the following precautions:

1. I have also Session Buddy installed that saves my sessions. If you have several Chromes installations with you account signed in and plugins sync, but do not have Session Buddy or something alike, then... You should, probably, install another session saving plugin, run all the installations, shut them down and afterwards do the upgrade. Because...
1. I've saved the session from the TGS settings to a text file.
1. Uninstalled the TGS, which lead to all suspended tabs to disappear on my laptop and in seconds on my desktop, which is synced. "OMG, I've lost the tabs, or at least I'm doomed to work through them one by one..." I thought.
1. Installed the new TGS, enabling the "use chrome tab suspending mechanism".
1. Tried to import the TGS exported session, which, surprise, contained one URL and the file was 33 bytes.
1. Thanks brain I've got another session history managing extension, so I've restored my sessions on both Chrome installations aaaand...

It seems like the Chrome is running faster and things are cozy and startup time seems to be better - around 10 seconds with 366 suspended tabs restored.

So, save your session and upgrade, having these precautions in mind.

**Comment by pluto00987** [comment]
See this thread too for backup/restore and manual update suggestions
https://github.com/deanoemcke/thegreatsuspender/issues/526

**Comment by adityabhaskar** [comment]
Ditto, but from 6.30.

One of my browser profiles has upgraded to 7.1.0, but the other two are stuck on 6.30. I wonder if this is due to staged roll out, or if there's another reason. Based on [this](https://github.com/deanoemcke/thegreatsuspender/milestone/1), all should have upgraded to 7.1.x.

@deanoemcke I also updated my [ClutterFree](https://chrome.google.com/webstore/detail/clutter-free-prevent-dupl/iipjdmnoigaobkamfhnojmglcdbnfaaf) extension to use message passing (#276 )  for unsuspending tabs.

This fails without warning for pre v 7.1.x users of TGS since default behaviour is:
- `null`/no-response for _success_ in 7.1.x, but
- `null`/no-response for no-op/failure in pre 7.1.0.

**Comment by primeos** [comment]
I'm also having this issue on Chromium but I'm stuck on version `7.0.109`.

When I open the background page  
(`chrome-extension://klbibkeccnjlkjkiokjodocebajanakg/_generated_background_page.html`) and request an update check via the console, Chromium does not find any updates (I would expect `update_available`):
```
$ chrome.runtime.getManifest().version
"7.0.109"
$ chrome.runtime.requestUpdateCheck(function(status, details) {console.log(status)})
no_update
```

Which is pretty weird and I don't know why (maybe a Chrom{e,ium} bug?).
Anyway, at least in my case it seems to be a problem with Chrome/Chromium rather than TGS.

**Comment by jasonbuechler** [comment]
Apparently the focus-stealing bug is a known issue/regression. Unfortunately, it was a bug introduced as part of the fix to the "chrome stealing focus when tab suspends" issue: #865, according to author

**Comment by ossilator** [comment]
as mentioned in [this comment](https://github.com/deanoemcke/thegreatsuspender/issues/865#issuecomment-521508449), the issue has been [reported against chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=994057), so you may want to watch that as well.
