### ISSUE TITLE
stop forcing updates

### ISSUE THREAD

**Issue by retrospec13** [deanoemcke/thegreatsuspender#989]
stop forcing updates

That's it.

**Comment by liamjohnston** [comment]
Without auto updates, the vast majority of users won't update. If you look at the issues raised, a big proportion are actually already fixed. 

If you don't want updates, run a local version rather than the web store version (instructions in readme).

**Comment by sirius16** [comment]
> Without auto updates, the vast majority of users won't update. If you look at the issues raised, a big proportion are actually already fixed.
> 
> If you don't want updates, run a local version rather than the web store version (instructions in readme).

Oh? Have the problems with disappeared tabs and session data been resolved? Well then, can you point me towards a resolution? My extension broke and I just know that I'll lose all my session data if I click "Repair"

**Comment by liamjohnston** [comment]
A couple more points. 

1. The vast majority of users don't experience tab loss issues during an update. Some people do, which is very unfortunate and is the only reason that updates to this extension are very rare. The current reasons for tab loss or extension corruption aren't fully known but a lot of time has gone into trying to combat this. 
2. Some bugs come about due to changes in chrome/chromium. I believe the focus stealing issue was a recent example of this. There’ve been others. The developer of this extension has no choice but to update this codebase to work with chrome, it can't work the other way around.

**Comment by RobertAb1** [comment]
It should be allowed to postpone updates few weeks. 
https://github.com/deanoemcke/thegreatsuspender/issues/988 is causing data loss, but it may be a fix at some point, and then it would be wise to update extension to this corrected version.

**Comment by retrospec13** [comment]
It definitely should because apps do not need to be updated for arbitrary
updates like this.

This was a "quality of life" update based on subjective decisions on the
dev.

Many people were fine with the original version.
